scikit-hep/uproot5

tests/test_0001-source-class.py, uproot4/source/xrootd.py
Adds an XRootD source that uses vector reads. This should probably be the only XRootD source.
By default it takes the number of chunks in a request by querying the server configuration:
```
time_profile(uproot4.source.xrootd.XRootDVectorReadSource(
"root://eospublic.cern.ch//eos/opendata/lhcb/AntimatterMatters2017/data/B2HHH_MagnetDown.root"
), basic_ranges)
```
However for now I've exposed this as a parameter, if only to make the performance studies easier:
```
time_profile(uproot4.source.xrootd.XRootDVectorReadSource(
"root://eospublic.cern.ch//eos/opendata/lhcb/AntimatterMatters2017/data/B2HHH_MagnetDown.root",
max_num_elements=5
), basic_ranges)
```
Related to #2.
=> Add XRootDVectorReadSource

tests/test_0023-more-interpretations-1.py, tests/test_0028-fallback-to-read-streamer.py, uproot4/compression.py, uproot4/deserialization.py, uproot4/model.py, uproot4/models/RNTuple.py, uproot4/models/TArray.py, uproot4/models/TAtt.py, uproot4/models/TBasket.py, uproot4/models/TBranch.py, uproot4/models/TLeaf.py, uproot4/models/TList.py, uproot4/models/TNamed.py, uproot4/models/TObjArray.py, uproot4/models/TObjString.py, uproot4/models/TObject.py, uproot4/models/TString.py, uproot4/models/TTree.py, uproot4/reading.py, uproot4/source/chunk.py, uproot4/source/cursor.py, uproot4/streamers.py
=> Fallback to reading streamer and raise better error messages on true failures.

README.md, setup.py, tests/test_0001-source-class.py, tests/test_0006-notify-when-downloaded.py, tests/test_0007-single-chunk-interface.py, tests/test_0008-start-interpretation.py, tests/test_0046-histograms-bh-hist.py, uproot4/extras.py, uproot4/source/xrootd.py
Apologies this PR grew a little as I wrote it, the commits should be self contained and easy to review individually. If you'd rather not have any of them (especially 52aa7f4 and a68a6bd) I'll rebase that commit out of the history.
In summary:
* Adds an extra to `setup.py` so `pip install -e .[testing]` allows the tests to be ran fully
* Makes some minor corrections to the test dependencies and what is used in `importorskip`
* Replaces `pyxrootd` with `XRootD` as `pyxrootd` is more of a private implementation detail that should be prefixed with an underscore
* Avoids a deadlock on exit (https://github.com/scikit-hep/uproot/issues/504) by using an `atexit` handler to cleanup open files (this should be made XRootD version dependent once fixed upstream …
=> XRootD improvements

uproot4/interpretation/jagged.py
Faster handling of the data masking required when header bytes are present.
Speeds up the reading of large std::vectors especially with multiple cores because the GIL usage is reduced.
=> optimize handling of header bytes

uproot4/behaviors/TH1.py, uproot4/behaviors/TH2.py, uproot4/behaviors/TH3.py
While moving some code from uproot3 to uproot4 I stumbled upon this error (trying to pull the values and errors from a `TH1D`:
```
In [19]: h.values_errors()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-19-431438897d77> in <module>
----> 1 h.values_errors()
~/.pyenv/versions/3.8.2/envs/tdub/lib/python3.8/site-packages/uproot4/behaviors/TH1.py in values_errors(self)
76         sumw2 = self.member("fSumw2", none_if_missing=True)
77         if sumw2 is not None and len(sumw2) == self.member("fNcells"):
---> 78             sumw2 = sumw2.reshape(values.shape)
79             positive = sumw2 > 0
80             errors[positive] = numpy.sqrt(sumw2[positive])
AttributeError: …
```
=> Fix error from calling `reshape` on TArrayD that lives inside of a TH1D

tests/test_pr0067-common-entry-offsets.py, tests/test_pr0067.py, uproot4/behaviors/TBranch.py
This used to be called "clusters" in uproot0 but is not strictly the
ROOT definition of clusters. Users may wish to partition reading
a TTree according to these offsets to prevent having to read and
decompress the same basket in multiple partitions.
=> Add function to retrieve common entry offsets among branches

uproot4/interpretation/identify.py
@tamasgal and @bernd1995, this fixes #74 and therefore provides a good model for tamasgal/UnROOT.jl#9. The information about a branch's dimensions are stored in the TLeaf's fTitle, and that needs to be parsed by a regex. The example @bernd1995 created had no leaf names:
```c++
tree_arr -> Branch("6dVec",&vec,"[6]/D");
tree_arr -> Branch("2x3Mat",&mat,"[2][3]/D");
```
as opposed to
```c++
tree_str -> Branch("2x3mat",&mat,"el[6]/D");
```
(where the leaf name is `"el"`), which I guess is legal, so the regex has to allow for that.
This CI is going to fail until I fix scikit-hep/awkward-1.0#416, which @tamasgal pointed out in another issue.
=> Minor tweak to regex to fix #74.

uproot4/__init__.py, uproot4/behaviors/TBranch.py, uproot4/containers.py, uproot4/interpretation/identify.py, uproot4/interpretation/numerical.py, uproot4/interpretation/objects.py, uproot4/source/file.py
This only fixes the strings case in scikit-hep/uproot#510, commented upon in https://github.com/scikit-hep/uproot4/issues/38#issuecomment-681161557. It doesn't touch the strangely split class.
=> Distinguish between 1-byte and 6-byte header in AsArray.

uproot4/behaviors/TBranch.py, uproot4/streamers.py
=> When searching for a streamer by member name, be sure to include a class's base classes.

tests/test_0087-memberwise-splitting-not-implemented-messages.py, uproot4/const.py, uproot4/containers.py, uproot4/deserialization.py, uproot4/model.py, uproot4/models/RNTuple.py, uproot4/models/TArray.py, uproot4/models/TAtt.py, uproot4/models/TBranch.py, uproot4/models/THashList.py, uproot4/models/TLeaf.py, uproot4/models/TList.py, uproot4/models/TNamed.py, uproot4/models/TObjArray.py, uproot4/models/TObjString.py, uproot4/models/TObject.py, uproot4/models/TRef.py, uproot4/models/TString.py, uproot4/models/TTree.py, uproot4/source/cursor.py, uproot4/streamers.py
This will remove the "bug" label from #38, but won't close it.
Now
```python
>>> import uproot4, skhep_testdata
>>> t = uproot4.open(skhep_testdata.data_path("uproot-issue510b.root"))["EDepSimEvents"]
>>> b = t["Event"]["Trajectories.Points"]
>>> b.array()
```
raises
```
NotImplementedError: memberwise serialization of AsArray
in file /python3.8/site-packages/skhep_testdata/data/uproot-issue510b.root
```
so it should be more clear that this is a missing feature, not a bug.
=> Check for memberwise serialization and raise NotImplementedError as needed.

tests/test_0053-parents-should-not-be-bases.py, uproot4/_util.py, uproot4/behaviors/TBranch.py, uproot4/containers.py, uproot4/interpretation/identify.py, uproot4/interpretation/library.py, uproot4/interpretation/objects.py, uproot4/model.py, uproot4/models/TList.py, uproot4/models/TObjArray.py, uproot4/reading.py, uproot4/source/cursor.py, uproot4/source/file.py, uproot4/source/futures.py, uproot4/source/http.py, uproot4/source/xrootd.py, uproot4/streamers.py
Uproot's deserialization is based on nominal versions of classes first, then falls back to streamers if they're wrong. Streamers being wrong can have you thinking you need to iterate over 1329201155 elements in a TObjArray before the error gets fixed. In Python 2, `range(1329201155)` constructs a list, which uses an enormous amount of memory. `uproot4._util.range` is `range` in Python 3 and `xrange` in Python 2; we just need to use `uproot4._util.range` wherever we'd use `range`.
Issue #36 warned that it might be a deep bug, affecting Python 3 in unknown and apparently invisible ways. It's not.
=> Fixes #36 by replacing range with xrange in Python 2.

uproot4/__init__.py, uproot4/behaviors/TBranch.py, uproot4/language/python.py, uproot4/model.py, uproot4/reading.py
Raised by @kratsg on Slack:
```python
Traceback (most recent call last):
...
File "/home/kratsg/pyhf/lib/python3.8/site-packages/uproot4/behaviors/TBranch.py", line 945, in arrays
arrays, expression_context, branchid_interpretation = _regularize_expressions(
File "/home/kratsg/pyhf/lib/python3.8/site-packages/uproot4/behaviors/TBranch.py", line 2881, in _regularize_expressions
_regularize_expression(
File "/home/kratsg/pyhf/lib/python3.8/site-packages/uproot4/behaviors/TBranch.py", line 2789, in _regularize_expression
for symbol in language.free_symbols(
File "/home/kratsg/pyhf/lib/python3.8/site-packages/uproot4/language/python.py", line 365, in free_symbols
raise uproot4.KeyInFileError(
uproot4.KeyInFileError: not found: 'mjj' because …
```
=> Homogenize uses of KeyInFileError

README.md, uproot4/behaviors/TBranch.py, uproot4/interpretation/__init__.py, uproot4/interpretation/grouped.py, uproot4/interpretation/jagged.py, uproot4/interpretation/library.py, uproot4/interpretation/numerical.py, uproot4/interpretation/objects.py, uproot4/interpretation/strings.py, uproot4/models/TBasket.py
As discussed in issue #90.
Corresponds to scikit-hep/awkward-1.0#448.
=> Set up interface between Uproot and Awkward so that Awkward can be used to optimize object-reading.

.github/workflows/build-test.yml
Cleaning up a little. setup-minconda has moved. GHA has added a new feature that allows the default shell to be set.
You still have way too many quotes on things that don't need them. :P
(But you are okay to put the contents of `run:` in without quotes?...)
=> ci: cleanup a bit

tests/test_0044-concatenate-function.py, uproot4/behaviors/TBranch.py, uproot4/interpretation/library.py, uproot4/language/python.py
So, for instance, if a user types
```python
tree.arrays()
```
and any branch names are things like `"what # ever"`, don't make that an expression; make `"get('what # ever')"` an expression instead.
Also noticed a blocking error (could not find previous iteration's basket data) in HasBranches.iterate if the expression is not the branch name. Fixing the above revealed that brittleness, and now it has been fixed.
Also simplified the metadata in `expression_context`.
=> Don't assume branch names are expressions

tests/test_0045-lazy-arrays-1.py, uproot4/behaviors/TBranch.py
The exception from `uproot4._util._file_not_found` was simply not raised.
=> Quickfix .lazy() when called on missing files. Fixes #120

.github/workflows/build-test.yml
We can instead use dependabot.yml to keep actions up via PRs every day or week when new changes are detected. In that case, we'd use v2.0.0 here.
This was released about 30 minutes ago, see https://github.com/conda-incubator/setup-miniconda/issues/84
=> fix: warning about GHA security

uproot/behaviors/TH1.py, uproot/behaviors/TH2.py, uproot/behaviors/TH3.py, uproot/behaviors/TProfile.py, uproot/behaviors/TProfile2D.py, uproot/behaviors/TProfile3D.py
The only change needed to catch up to
https://github.com/henryiii/uhi/blob/9fcfdc6158c686e58dfd31728b0aef4bd9572abe/uhi/typing/plottable.py
was to rename `interpretation` as `kind` and make its output all upper-case.
@henryiii @HDembinski, this should be ready for the non-release-candidate release, which I'll be starting now (first Awkward Array, then Uproot; should be about half an hour).
=> Catch up to the latest histogram protocol.

uproot/_util.py, uproot/containers.py, uproot/interpretation/jagged.py, uproot/interpretation/library.py, uproot/interpretation/objects.py, uproot/interpretation/strings.py, uproot/streamers.py
I'm playing with cutting edge NumPy and I got some warnings in unit tests from deprecations triggered in uproot. [NumPy v1.20 deprecates](https://numpy.org/devdocs/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated) using `numpy.builtin` over `builtin` (e.g. `numpy.object` instead of `object`). The one change in this PR that I'm not sure about is `numpy.long --> numpy.compat.long`. This is necessary if uproot4 is supporting Python 2, but if Python 3 is required the change can be `numpy.long --> int`.
=> Fix warnings associated with NumPy deprecations.

uproot/extras.py
From @ryuwd on https://gitter.im/Scikit-HEP/uproot:
> I am using `uproot4.iterate` to read files over xrootd - I am currently seeing this error at exit after the script has completed all its tasks:
> 
> ```
>     ERROR    | Error in atexit._run_exitfuncs:
>     ERROR    | Traceback (most recent call last):
>     ERROR    |   File "/XicpStToXicpPiPi/.snakemake/conda/3c5bbdd0/lib/python3.8/site-packages/uproot4/extras.py", line 112, in cleanup_open_files
>     ERROR    | if isinstance(obj, XRootD.client.file.File) and obj.is_open():
>     ERROR    | ReferenceError
>     ERROR    | :
>     ERROR    | weakly-referenced object no longer exists
>     ERROR    | Error in atexit._run_exitfuncs:
> ```
My response:
> Uproot has one `atexit` handler, which runs when the script is done, and …
=> Hide ReferenceError in XRootD atexit.

.github/workflows/build-test.yml, requirements-dev.txt, requirements-test.txt, tests/test_0240-read_TGraphAsymmErrors.py, uproot/behaviors/TGraphAsymmErrors.py
here's a test script to work with
```python
import uproot
import os.path
fname = "HEPData-ins1755298-v3-Expected_limit_1lbb.root"
if not os.path.isfile(fname):
with open(fname, 'wb') as f:
import requests
response = requests.get("https://www.hepdata.net/download/table/ins1755298/Expected%20limit%201lbb/3/root")
response.raise_for_status()
f.write(response.content)
f = uproot.open(fname)
graph = f['Expected limit 1lbb/Graph1D_y1']
graph.values()
graph.errors()
```
=> feat: Add TGraphAsymmErrors

tests/test_0001-source-class.py, tests/test_0006-notify-when-downloaded.py, tests/test_0007-single-chunk-interface.py, uproot/source/xrootd.py
Since i also ran into #122 i would like to help fixing it. I believe better than falling back to non-vector reads in case a single request is larger than the maximum the server allows would be chunking the request into smaller parts as i think [ROOT does it](https://root.cern/doc/master/TNetXNGFile_8cxx_source.html#l00469). The relevant code is probably that part:
```cpp
// If the length is bigger than max readv size, split into smaller chunks
if (length[i] > fReadvIorMax) {
Int_t nsplit = length[i] / fReadvIorMax;
Int_t rem    = length[i] % fReadvIorMax;
Int_t j;
// Add as many max-size chunks as are divisible
for (j = 0; j < nsplit; ++j) {
offset = position[i] + (j * fReadvIorMax);
chunks.push_back(ChunkInfo(offset, fReadvIorMax, cursor));
cursor += fReadvIorMax;
}
// Add the remainder …
```
=> Split vector reads into smaller chunk when single requests are larger than `max_element_size`

.github/workflows/build-test.yml, README.md, uproot/source/xrootd.py
Fixes #253 
This change just prevents the length of any sublist in `all_request_ranges` from exceeding the `readv_iov_max` limit.
=> Prevent the xrootd server readv_iov_max limit from being exceeded

tests/test_0001-source-class.py, uproot/source/xrootd.py
When requesting a single chunk with `uproot.source.xrootd.XRootDSource` the arguments have to be eventually casted to (python) int before giving them to `pyxrootd.client.File.read`, otherwise it will throw an exception. This happenend when requesting data via `uproot.TBranch.basket` because that passes the parameters through as `np.int64` (coming from `branch.member("fBasketSeek")`:
```pycon
>>> import uproot
>>> branch = uproot.open("root://eospublic.cern.ch//eos/root-eos/cms_opendata_2012_nanoaod/Run2012B_DoubleMuParked.root:Events/Muon_pt")
>>> branch.basket(0)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/home/nikolai/python/uproot4/uproot/behaviors/TBranch.py", line 2484, in basket
chunk, cursor = self.basket_chunk_cursor(basket_num)
File …
```
=> Cast start and length to int before passing to pyxrootd.client.File.read

docs-sphinx/basic.rst
Update the basic.rst documentation, in the section "Computing expressions and cuts",
with an example of the conditional cut using the python syntax and explicitly with the
parentheses. Without the parentheses a TypeError will occur, and it is not necessarily
obvious when coming from ROOT and C++ syntax.
=> Update basic.rst with conditional cut example

tests/test_0240-read_TGraphAsymmErrors.py
The TGraphAsymmErrors tests all assume that a ROOT file can be supplied by
https://www.hepdata.net/download/table/ins1755298/Expected%20limit%201lbb/3/root
However, this URL now returns a page saying, "Converter error encountered." Perhaps the file has been deleted or moved? Could we instead put it in [scikit-hep/scikit-hep-testdata](https://github.com/scikit-hep/scikit-hep-testdata) like the others, @kratsg?
At the end of scikit-hep/uproot4#240, we were talking about the possibility of setting up something that delivers test files. This would be an instance in which relying on a third-party server is a problem, though putting everything into a GitHub repo (scikit-hep-testdata) is not a great solution, either, because of the PyPI file limits and the fact that these data are not really …
=> Skip some tests because HEPData isn't producing the source file anymore.

tests/test_0278-specializations-for-TParameter.py, uproot/__init__.py, uproot/behaviors/TParameter.py
This was requested by @WenzDaniel on Gitter. It's good to have an example of a class with `<int>` in its name to introduce a way to generate behaviors for any numeric specialization (though I still need to move `behavior_of` out of `__init__.py`).
=> Add specialized behaviors for TParameter, including generic dispatch for '<number>' templates.

uproot/source/xrootd.py
In
https://github.com/scikit-hep/uproot4/blob/fc32791d3cb420ed95ded64ce544a6ca1484f481/uproot/source/xrootd.py#L221-L225
If the readv request fails, then a `NoneType` `response` can be returned to the `callback` function, which causes a cryptic traceback to be printed complaining that the `response` object has no `chunks` attribute.
This PR doesn't fix any underlying issue, but printing an error message from the xrootd server will show what is going wrong.
=> XRootD: raise an exception if read_vector failed

uproot/source/futures.py
This helps to break reference cycles in the future notifier, which improves the plot from https://github.com/scikit-hep/uproot4/issues/294#issuecomment-790984804 to:
=> Remove Future attributes once done with them

tests/test_0017-multi-basket-multi-branch-fetch.py, uproot/behaviors/TBranch.py, uproot/model.py, uproot/models/TBranch.py, uproot/models/THashList.py, uproot/models/TLeaf.py, uproot/models/TList.py, uproot/models/TNamed.py, uproot/models/TObjArray.py, uproot/models/TObjString.py, uproot/models/TTree.py, uproot/streamers.py
Targeting specifically Chunk and TBasket objects, because they are some of the heaviest intermediate results.
Testing with the following:
```python
import uproot
import psutil
import time
import tqdm
import gc
def getmallinfo():
import ctypes
class MallInfo(ctypes.Structure):
_fields_ = [(name, ctypes.c_int)
for name in ('arena', 'ordblks', 'smblks', 'hblks', 'hblkhd',
'usmblks', 'fsmblks', 'uordblks', 'fordblks',
'keepcost')]
libc = ctypes.CDLL("libc.so.6")
mallinfo = libc.mallinfo
mallinfo.argtypes = []
mallinfo.restype = MallInfo
return mallinfo()
uproot.open.defaults["num_workers"] = 10
usage = []
def collect_usage(asize):
otype = uproot.source.chunk.Chunk
mallinfo = getmallinfo()
usage.append({
"dt": time.time() - tstart,
"rss": process.memory_info().rss,
"arraysize": asize, …
```
=> Remove more cycles and release heavy stuff early

uproot/deserialization.py
Running into issues where `bcnt` is absurdly large and it might be due to missing behavior in the `uproot4` implementation of `read_object_any` compared to ROOT's: https://github.com/root-project/root/blob/c4aa801d24d0b1eeb6c1623fd18160ef2397ee54/io/io/src/TBufferFile.cxx#L2764-L2765
Specifically, I expect around 1080 bytes for this object serialized in a ROOT file, but `bcnt` is `1073742891`.
```
(Pdb) mycursor.fields(chunk, _numbytes_version_1, context, move=False)
(1073742891, 0)
(Pdb) num_bytes = numpy.int64(1073742891)
(Pdb) bool(num_bytes & uproot.const.kByteCountMask)
True
(Pdb) int(num_bytes & ~uproot.const.kByteCountMask) + 4
1071
```
so there's clearly perhaps missing behavior in masking it to get the proper bytecount out.
=> feat: add bytecount mask as part of read_object_any

tests/test_0302-pickle.py, uproot/cache.py, uproot/source/chunk.py, uproot/source/file.py, uproot/source/http.py, uproot/source/xrootd.py
Cutting off at the resource acquisition.
The only negative I can think of is it might take people by surprise that the pickle does not completely contain the original data. But I also hope they do not expect it to behave like that.. probably worth a warning in the docs?
=> Allow all sources and caches to be pickled

.github/workflows/build-test.yml, tests/test_0167-use-the-common-histogram-interface.py
I need to figure out what's going on with `uproot-issue33.root` conversion into boost-histogram. If I remember right, it's a histogram with labels.
Oh, and @henryiii, you might be interested in this.
=> Histograms should be part of the regular tests.

tests/test_0043-iterate-function.py, tests/test_0240-read_TGraphAsymmErrors.py
Specifically, scikit-hep/scikit-hep-testdata#51. There were a couple of places where I used `data_path` to get the location of a file and then modified it to the name of another file I knew existed. Now they don't necessarily exist until you explicitly call `data_path` on them.
=> Adjust to the new scikit-hep-testdata.

src/uproot/source/xrootd.py
Looking at the changes from #334 i noticed that the `HTTPSource` calls `shutdown` on it's `ResourceThreadPoolExecutor`. I also have to do that for the `ResourceThreadPoolExecutor` i introduced in #243 because `XRootDSource` also has it's own `__exit__` method. It also has to be the `shutdown` method of the executor and not `__exit__`, because `__exit__` will try to call `__exit__` on the Resources and i set the resources in the `ResourceThreadPoolExecutor` of `XRootDSource` to `None`, because it's just there to merge chunks from vector reads that had to be split up.
Before that fix, reading with `XRootDSource` was also leaking threads:
```python
import uproot
for i in range(10):
with uproot.open(
"root://eospublic.cern.ch//eos/root-eos/cms_opendata_2012_nanoaod/Run2012B_DoubleMuParked.root …
```
=> Shutdown the ThreadPoolExecutor in XRootDSource on exit (stop leaking threads in XRootDSource)

src/uproot/reading.py, src/uproot/source/http.py, src/uproot/version.py
`ROOT`'s `TFile::Open` supports transparent access not just to HTTP, but also HTTP with basic authentication, by embedding the username and password in the URL, e.g. `http(s)://username:password@example.org/path/to/file.root`. This provides a some level of security to your precious data which you may not want to make public (yet?). In practice, hosting files this way with some credentials widely known to a collaboration is used a fair amount to expose data in academic clusters. 
This pull request adds equivalent functionality to uproot. `urllib`'s parser already parses the username and password from an URL, so we can grab the credentials from the parsed_url when available and append them to the headers. Note that this is only secure at all when using HTTP, as otherwise any interloper can …
=> Add support for basic HTTP authentication

src/uproot/behaviors/TGraph.py, src/uproot/behaviors/TGraphErrors.py, src/uproot/models/TGraph.py, src/uproot/models/TH.py
This addresses the issue raised in https://github.com/scikit-hep/uproot4/pull/352#issuecomment-841758979
I had forgotten that the mechanism that discovers behavioral mix-ins and applies them to classes only does so if the models are generated from streamers. If they're explicitly defined, then I can make the inheritance manually and statically. (It's more flexible and less magical, but I have to remember to do it!)
@matthewfeickert, can you let me know if this fixes your CI?
=> Explicit models need explicit behaviors.

setup.cfg, src/uproot/extras.py, src/uproot/reading.py, src/uproot/source/xrootd.py
Now that there are versions assigned for the two XRootD workarounds I think it would be better to apply them conditionally. There are a few ways of doing this but I think using `pkg_resources` is the simplest while maintaining support for Python 2.
=> Conditionally apply XRootD workarounds based on it's version

.github/workflows/deploy.yml, setup.cfg
Following our guidelines.
@jpivarski  We should set up a scikit-hep token to upload just this package instead of using a username, which is not as safe. I can make this change (I'll need to remove the username and add the generated token as the password).
=> ci: use guidelines for deploy

src/uproot/extras.py
When one builds XRootD, the version number differs from the standard `x.y.z` - it is, e.g., `v20210712-58b374f12`, which causes `LooseVersion` to raise `TypeError`.
Fixes #394
=> Treat self-built XRootD version strings

tests/test_0220-contiguous-byte-ranges-in-http.py
This test is missing the pytest network mark despite trying to access a webserver at cern.ch
=> mark test 0220 with network tag

src/uproot/interpretation/identify.py, src/uproot/interpretation/numerical.py
Tested on files made by https://root.cern/doc/master/float16_8C_source.html with
```c++
Float16_t fI14; //[-pi,pi,14] saved as a 14 bit unsigned int
```
replacing `14` with `20`, `32`, `33`, `0`, `1`, and `2`. Values outside of the legal range, `2 <= num_bits <= 32`, are _left in the file_ and have to be mapped to `32`, even for `Float16_t`.
=> Float16_t with up to 32 bits is allowed (not just 16).

src/uproot/writing/_cascade.py
After the release, I made a first performance test of writing histograms. Here's the script:
**scaling-histograms-uproot.py**
```python
import time
import numpy as np
import uproot
import hist
with uproot.recreate("output.root", compression=None) as file:
for nbins in 5, 5000, 10, 2000, 20, 1000, 50, 500, 100, 200:
starttime = time.time()
for i in range(1000):
h = hist.Hist.new.Reg(nbins, -5, 5).Weight()
file["h_%05d_%05d" % (nbins, i)] = h
print(f"{nbins = }, time = {(time.time() - starttime)}")
```
The performance was terrible.
```
% python scaling-histograms-uproot.py 
nbins = 5, time = 2.9465341567993164
nbins = 5000, time = 7.75829005241394
nbins = 10, time = 12.314059019088745
nbins = 2000, time = 17.434439659118652
nbins = 20, time = 22.311167001724243
nbins = 1000, time = …
```
=> Fixed performance bug in large directories

src/uproot/writing/writable.py
(As discussed before on Gitter)
Truncate the file to 0 bytes opened with uproot.recreate before writing contents. This behavior agrees with ROOT Recreate.
The previous code lines seemed to intend to do this, however assumingly due to an erroneous 'not', this was not done.
If the file does not exist, an empty file is created. This is the same behavior as before.
=> Recreate truncates if file exists

src/uproot/_util.py, src/uproot/behaviors/TBranch.py, src/uproot/models/TRef.py
If a sub-branch cannot be optimized by awkward, the parent cannot either and must have its form fixed for use with lazy arrays.
=> Recursively fix forms for objects that require ak.from_iter

src/uproot/interpretation/library.py
Pandas turns the "None" values of a MultiIndex into NaN, and then they're not good keys for dict lookup. The "filler" to use when leaf-lists (multiple levels of column name structure) and non-leaf-lists (single level) are mixed must be empty strings, rather than "None".
=> Leaf-lists (structs) and non-leaf-lists in the same Pandas DataFrame.

src/uproot/interpretation/identify.py, tests/test_0438-TClonesArray-is-not-AsGrouped.py
But the second bug offers no clues as to how it can be solved.
Here's the issue: according to TObject's streamers (and a lot of other things), `fBits` is 4 bytes.
```python
>>> import uproot
>>> t = uproot.open("uproot-issue-438b.root:Delphes")
>>> t.file.streamer_named("TObject").show()
TObject (v1)
fUniqueID: unsigned int (TStreamerBasicType)
fBits: unsigned int (TStreamerBasicType)
```
This is also true of _almost_ all of the `fBits` branches:
```python
>>> for x in t.keys(filter_name="*.fBits"):
...     print(f"{len(t[x].debug_array(0)) / 4:10} {x}")
... 
1.0 Event/Event.fBits
1.0 Weight/Weight.fBits
7924.5 Particle/Particle.fBits
273.0 Track/Track.fBits
819.0 Tower/Tower.fBits
273.0 EFlowTrack/EFlowTrack.fBits
477.0 EFlowPhoton/EFlowPhoton.fBits
267.0 …
```
=> Fixes both bugs in issue #438.

src/uproot/writing/_cascadetree.py
Although PyROOT's iteration only looks at the `fLeafCount` member to determine the number of subentries, `TTree::Scan`, `TTree::Draw`, and `TTreeReader` all seem to be parsing the text of the leaf to determine how to count the subentries.
See discussion in #457.
=> Set leaf title to 'branchname[countername]' for jagged arrays.

src/uproot/extras.py, src/uproot/reading.py
Resolves #486. Checks for the package name `pyxrootd` if searching for `XRootD` fails.
=> Detect XRootD versions before 4.11.1

src/uproot/behaviors/TBranch.py, src/uproot/models/TBasket.py, src/uproot/reading.py, src/uproot/source/chunk.py, src/uproot/source/file.py, tests/test_0519-remove-memmap-copy.py
Dear `uproot4` developers,
this PR removes unnecessary(?) copies of the `numpy.memmap`. This should be safe, as `self._file` is only opened in `r`-mode, see: https://github.com/scikit-hep/uproot4/blob/8ae497a89ec92f06724980fccafa1c4286ce6040/src/uproot/source/file.py#L113 `uproot3` also did not do copies on the `numpy.memmaps`: https://github.com/scikit-hep/uproot3/blob/master/uproot3/source/memmap.py#L54-L57
Since this is a very fundamental piece of code I would really appreciate your feedback here!
(I hope I did not overlook a trivial reason why now a copy is needed.)
Thank you very much for reviewing!
Best, Peter
=> [MemmapSource] Remove unnecessary(?) copies

src/uproot/models/TTable.py, tests/test_0418-read-TTable.py
My original plan to "publish" them was to do so by adding `@property` accessors without the underscore, but to simply rename might be even better.
=> Remove underscore prefixes from data members uproot.model.TTable

src/uproot/model.py
There are actually two memory leaks: one is in Uproot. This one is due to the fact that ROOT instance versions can sometimes be `0` while the class version is something else, and Uproot was repeatedly redefining the class, which was both slow and contributed to global memory (because they're new classes). The commit in this PR fixes that (checks for instance version `0` and no matching `known_version`, tries maximum `known_version` instead).
The other memory leak is in NumPy: https://github.com/numpy/numpy/issues/6581#issuecomment-1012678379
If you follow the thread back, people have been talking about it since 2009 (SciPy ticket 1003, ported to GitHub in 2012, superceded by the above issue in 2015, and there's an open PR https://github.com/numpy/numpy/pull/15065, last touched in 2021). …
=> Fixed one memory leak in complex objects

src/uproot/sink/file.py, src/uproot/writing/writable.py
`FileSink` seems to be designed such that it can also handle file objects. The only thing that is blocking this functionality is that `FileSink.from_object` does not return anything, which I assume is a mistake.
This change adds the missing return statement and a bit of documentation to open/recreate/update.
=> Allow reading and writing from/to already opened files

src/uproot/containers.py
=> Restore performance hack for AsArray(True, False, AsVector(False, dtype)).

src/uproot/writing/identify.py, tests/test_0580-round-trip-for-no-flow-histograms.py
This should replace #580.
Instead of padding and removing padded bins, this PR just corrects Uproot's understanding of what hist means by `flow=True` on histograms with no built-in flow bins. It removes a bug in histogram-writing, but everything else stays the same.
This PR also doesn't address Uproot's and hist's disagreement about whether `axes[0].edges` is a property or a method, but that would be an API breaking change. This PR also changes behavior, but it's unequivocally a bug fix. Uproot was previously assuming something wrong about how hist behaves and was writing corrupted ROOT files as a result. If anyone finds this PR, searching for an explanation for the change in behavior, the old behavior was wrong and you should re-write your files of histograms.
This PR _does not_ need to …
=> In hist, flow=True only has flow bins if the histogram object has them.

src/uproot/__init__.py, src/uproot/containers.py, src/uproot/interpretation/identify.py, src/uproot/interpretation/objects.py, tests/test_0589-explicitly-interpret-RVec-type.py
It's just like the one for `std::vector`, but I didn't see any differences in how the two are encoded. If there are such differences, we should modify the new `RVec` code.
=> Add explicit interpreter for ROOT::VecOps::RVec.

src/uproot/exceptions.py
(about 20 ms) by limiting damerau_levenshtein to 1000 strings.
I seem to remember this being an issue for you, @kratsg, because something was using `try`-`except KeyInFileError` to determine whether a key exists in files with _lots_ of keys. The damerau_levenshtein algorithm is for helping users find a mistyped key, but we don't want it hurting automated processes.
=> Put an upper limit on the time KeyInFileError takes to print itself

tests/test_0341-manipulate-streamer-info.py
This PR just removes 2 tests.
The tests used to be:
1. put a TObjString in the ROOT file along with a TObjString streamer
2. update the file in ROOT (adding a histogram)
3. see that ROOT has added the histogram streamers in addition to the TObjString
Now ROOT adds the histogram streamers, but removes the TObjString streamer. This is probably not considered an error because TObjString is a fundamental, built-in type. But still, we can't do our test now.
=> Adjust for ROOT TStreamerInfo change.

src/uproot/_util.py, src/uproot/behaviors/TBranch.py, src/uproot/containers.py, src/uproot/interpretation/__init__.py, src/uproot/interpretation/grouped.py, src/uproot/interpretation/identify.py, src/uproot/interpretation/jagged.py, src/uproot/interpretation/library.py, src/uproot/interpretation/numerical.py, src/uproot/interpretation/objects.py, src/uproot/interpretation/strings.py, src/uproot/model.py, src/uproot/models/TArray.py, src/uproot/models/TAtt.py, src/uproot/models/TDatime.py, src/uproot/models/TGraph.py, src/uproot/models/TH.py, src/uproot/models/TNamed.py, src/uproot/models/TObjString.py, src/uproot/models/TObject.py, src/uproot/models/TRef.py, src/uproot/models/TString.py, src/uproot/streamers.py, tests/test_0034-generic-objects-in-ttrees.py, tests/test_0341-manipulate-streamer-info.py
Instead of `index_format, header, tobject_header, breadcrumbs`.
This change makes it possible to add as many arguments to `awkward_form` as we need.
=> awkward_form arguments are now (self, file, context).

src/uproot/__init__.py, src/uproot/_util.py, src/uproot/behaviors/TBranch.py, src/uproot/behaviors/TTree.py, src/uproot/models/TTree.py, tests/test_0609-num-enteries-func.py
Usage commands:
```python
import uproot
import skhep_testdata
from pprint import pprint as pp
file1 = skhep_testdata.data_path("uproot-Zmumu.root") + ":events"
file2 = skhep_testdata.data_path("uproot-HZZ.root") + ":events"
```
Outputs:
```python
>>> pp(uproot.num_entries(file1))
[(2304,)]
>>> pp(uproot.num_entries([file1,file2]))
[(2304,), (2421,)]
```
Tests, docstring and cleanup: WIP
=> Add the uproot4.num_entries function

src/uproot/containers.py, src/uproot/interpretation/__init__.py, src/uproot/interpretation/identify.py, src/uproot/interpretation/jagged.py, src/uproot/interpretation/library.py, src/uproot/interpretation/objects.py, src/uproot/model.py, src/uproot/version.py
AsJagged was missing.
Also, I made sure that the docstrings reflect the arguments as they are.
And we never create a dict and pass it in anymore; we let the default arguments do their work.
This will have to be cherry-picked and put onto `main` as well.
=> Cleanly ensure all Interpretation.awkward_form signatures have been reverted.

src/uproot/reading.py
This was a dumb mistake, pointed out by Andrew Wightman (Notre Dame) with a file of 61944 histograms.
Since names are not unique identifiers for objects in TDirectories, the `uproot.TDirectory.__getitem__` was iterating through the list, looking for matches. If you do that _n_ times, the time complexity is _O(n²)_.
However, names are _almost_ unique identifiers for objects in TDirectories, so I added a `uproot.TDirectory._keys_lookup`, which is a hashmap from names to lists of matching indexes in `uproot.TDirectory._keys`. For a given name, the number of items to search through is much shorter, usually 1.
This reduces the time needed to read the 61944 from 206 seconds to 54 seconds. Most importantly, it's flat: both the first and the last 1000 histograms take 0.85 seconds, whereas before …
=> Iterate over objects in TDirectory in linear time.

src/uproot/reading.py
=> Set ReadOnlyDirectory attributes when fSeekKeys == 0

src/uproot/_util.py, src/uproot/behaviors/TBranch.py, src/uproot/reading.py
Backport of #660 to `main-v4`, fixes #658
=> [v4 backport] Set ReadOnlyDirectory attributes when fSeekKeys == 0

src/uproot/_util.py
So if a path from `pathlib.Path` _starts with_ "http:/" and _no second slash_ (also for "file", "https", "root" URL schemes, case insensitive), then a second slash will be added.
`pathlib.Path` is our recommended way of saying, "This really is a path, even though it has a colon in it," but we didn't foresee this issue with _URLs_ with colons in them.
There's another way of doing it with `{filename: None}` instead of `pathlib.Path(filename)`, which doesn't suffer from this, but enough people are probably doing the `pathlib.Path` thing that we need this small correction.
=> pathlib.Path drops '//' (naturally), but it's sometimes used for URLs

src/uproot/writing/identify.py, tests/test_0422-hist-integration.py
Doesn't fully support categorical axis round-trip from hist through TH*, but at least it gets the number of overflow bins right (fixing #659).
=> Gets the number of overflow bins for hist.axis.IntCategory, at least.

src/uproot/streamers.py, tests/test_0643-reading-vector-pair-TLorentzVector-int.py
@aryan26roy, does this one get read properly through AwkwardForth, when this commit is ported to your branch?
=> Prevent std::pair from being AsStridedObjects.

src/uproot/writing/identify.py, tests/test_0651-implement-transformed-axis.py
Because not implementing it means that users get the wrong data.
=> Implement transformed axis from boost-histogram/hist.

src/uproot/writing/identify.py, tests/test_0651-implement-transformed-axis.py
This is the `main-v4` version of #675.
=> Implement transformed axis from boost-histogram/hist (v4).

src/uproot/containers.py
This fixes the direct error that #607 saw, though this data type is likely too complex to solve all of its issues. I see an infinite loop:
```
uproot.deserialization.DeserializationError: while reading
MGTEvent version 9 as uproot.dynamic.Model_MGTEvent_v9 (6286 bytes)
(base): <MGTDataObject (version 2) at 0x7f8c73766fa0>
(base): <MGVMemoryCheckable (version 1) at 0x7f8c73766b50>
fEventType: 16469
fETotal: -1.82467463945584e-05
fTime: 3.6780645929512914e+267
fWaveforms: None
fDigitizerData: None
MGTEvent version 9 as uproot.dynamic.Model_MGTEvent_v9 (24441 bytes)
(base): <MGTDataObject (version 2) at 0x7f8c7371a160>
(base): <MGVMemoryCheckable (version 1) at 0x7f8c7371a1c0>
fEventType: 16608
fETotal: 1.0222966365301011e-196
fTime: 3.7243961167525673e+267
MGTEvent version 9 as …
```
=> AsDynamic has no self._header.

src/uproot/const.py, src/uproot/models/RNTuple.py
```python
akako@archlinux ~/D/g/uproot4 (RNTuple)> python -c 'from pprint import pprint; import uproot as up; import 
skhep_testdata; filename = skhep_testdata.data_path("test_ntuple_large_bit_int64.root"); r = up.open(filena
me)["ntuple"]; pprint(r.arrays(entry_start=1, entry_stop=2).to_list())'
[{'one_bit': True, 'two_int64': 1}]
akako@archlinux ~/D/g/uproot4 (RNTuple)> python -c 'from pprint import pprint; import uproot as up; import 
skhep_testdata; filename = skhep_testdata.data_path("test_ntuple_large_bit_int64.root"); r = up.open(filena
me)["ntuple"]; pprint(r.arrays(entry_start=11111112, entry_stop=11111113).to_list())'
[{'one_bit': True, 'two_int64': 11111112},
{'one_bit': True, 'two_int64': 11111113}]
```
the `one_bit` field is not being read out correctly because it's actually …
=> Multiple clusters support for RNTuple

setup.cfg, src/uproot/_util.py, src/uproot/extras.py
This should not be pulled from setuptools vendoring, it's a standalone package. And `importlib.metadata.version` is the correct way to get the version (or from the backport `importlib_metadata`).
=> fix: depend on packaging, not setuptools vendored packaging

.github/workflows/build-test.yml
Saves some time for repeated pushes (including pre-commit fixes). Also allows Actions to run on a branch-to-branch PR, or manually.
=> ci: autocancel repeated runs

src/uproot/extras.py
This also addresses https://github.com/scikit-hep/uproot5/pull/652#discussion_r948495191, but is more up-to-date.
It _replaces_ #680, which should be closed.
=> docs: Installation requirements and error text for dask/dask-awkward in extras.py

tests/test_0652_dask-for-awkward.py
dask-awkward assumes that `ak.Array((1, 2, 3))` makes an `ak.Array`, the same as `ak.Array([1, 2, 3])`, which is a sensible assumption.
https://github.com/scikit-hep/awkward/pull/1614 accidentally changed that, and while one accidental consequence was for the better (`ak.from_iter({"one": 1, "two": 2, "three": 3})` no longer returns `ak.Array(["one", "two", "three"])`), it's reasonable to suppose that a _top-level_ tuple is intended to become an `ak.Array`, especially if passed to the `ak.Array` constructor.
https://github.com/scikit-hep/awkward/pull/1642 fixes it (best of both worlds), but Uproot tests would fail until this comes through. Therefore, this fix removes the tests that trigger the incompatibility. It should be merged into any Uproot PRs that are failing because of it. …
=> fix: Avoid triggering temporary dask-awkward/awkward incompatibility.

.github/workflows/semantic-pr-title.yml
The semantic-pr-title workflow does not currently run in a concurrency group. This means that subsequent pushes do not cancel in-progress actions. The following PR fixes this.
=> ci: use concurrency group for `semantic-pr-title`

src/uproot/writing/identify.py, tests/test_0013-rntuple-anchor.py, tests/test_0412-write-multidimensional-numpy-to-ttree.py, tests/test_0651-implement-transformed-axis.py
Equivalent of #698. This is an important bug-fix and must be back-ported.
=> fix: Do not write incorrect fSumw2 in histograms (v4).

src/uproot/__init__.py, src/uproot/_dask.py, tests/test_0700-dask-empty-arrays.py
=> fix: Fixes uproot.dask bug with empty branches

src/uproot/models/TTree.py
Long term I think we should be dealing with a per-process pool rather than a per-source pool, but that's a bigger task.
Fixes #712 
@alexander-held would you be able to check that this works in your context w/o any changes to `HTTPSource.__del__`?
=> fix: use ctx manager to ensure resources are freed

tests/test_0350-read-RooCurve-RooHist.py
This is needed for all PRs targeting `main`.
It should be fast-tracked into `main` so that it can be used in all those PRs.
=> test: adjust for boost-histogram 1.3.2's _storage_type deprecation.

tests/test_0350-read-RooCurve-RooHist.py
This is needed for all PRs targeting `main-v4`.
It should be fast-tracked into `main-v4` so that it can be used in all those PRs.
=> test: adjust for boost-histogram 1.3.2's _storage_type deprecation (v4).

src/uproot/reading.py
This is the "v4" version of #715.
Like the other in-flight PRs, it will follow this procedure:
1. #720 gets approved and merged into `main-v4`.
2. This PR updates to `main-v4`.
3. The tests re-run and pass (again).
4. This PR gets approved and merged into `main-v4`.
=> fix: ReadOnlyDirectory should provide the largest abs(cycle) when cycle is unspecified, not the largest cycle (v4).

.github/workflows/build-test.yml, tests/test_0001-source-class.py
Added in #742, was tracking https://github.com/actions/python-versions/pull/189, and fixed in https://github.com/actions/setup-python/issues/512.
=> ci: remove GHA workaround for macOS Python 3.11

src/uproot/_awkward_forth.py, src/uproot/_dask.py, src/uproot/_util.py, src/uproot/containers.py, src/uproot/deserialization.py, src/uproot/exceptions.py, src/uproot/interpretation/identify.py, src/uproot/interpretation/numerical.py, src/uproot/interpretation/objects.py, src/uproot/source/cursor.py, src/uproot/source/http.py, src/uproot/source/xrootd.py, src/uproot/writing/writable.py
I've added a few cleanups based on `pipx run refurb src`. I didn't work on else after return (there's a lot of them), or on ones that were not clearly an improvement, but I liked these.
- chore: remove extra returns
- chore: using copy for dicts (better readability)
- chore: nicer strings and comparisons
- chore: use contextlib.suppress
=> chore: some cleanup inpsired by refurb

src/uproot/models/TBasket.py, tests/test_0750-avoid-empty-TBasket-issue.py
The issue is that these files apparently don't have a second TKey. See https://github.com/scikit-hep/uproot5/issues/750#issuecomment-1270469267.
=> fix: avoid empty TBasket issue in embedded TBasket

src/uproot/models/TBasket.py, tests/test_0750-avoid-empty-TBasket-issue.py
This is the backport version of #751.
=> fix: avoid empty TBasket issue in embedded TBasket (v4)

src/uproot/_dask.py, tests/test_0755-dask-awkward-column-projection.py
Include the `project_columns` method in the existing callable classes as described in #725.
Ready for review. cc @jpivarski @douglasdavis 
I wasn't sure how to test this though, any suggestions?
=> feat: Added column_projection optimization

.github/workflows/build-test.yml
Committed via https://github.com/asottile/all-repos
=> ci: update to Python 3.11 final

src/uproot/behaviors/TH1.py, src/uproot/behaviors/TH2.py, src/uproot/behaviors/TH3.py, src/uproot/version.py, src/uproot/writing/identify.py, tests/test_0167-use-the-common-histogram-interface.py, tests/test_0422-hist-integration.py
Currently the `fSumw2` (weights) are not being correctly read/written when performing conversion to/from `hist`/`boost` histograms.
This is causing issues in https://github.com/scikit-hep/uproot5/issues/672 and solving this will also close https://github.com/scikit-hep/uproot5/issues/722.
- We now use `hist` `storage_type` property to check wether it's a weighted histogram or not, instead of the `variances` which is always defined and was cuasing false positives.
- Add two new tests, to check the conversion with a histogram with weights and another one without weights.
- Updated slicing of values / variances for categorical axes.
- Refactored `weighted` property and `to_boost` method to use inheritance.
- Write test for 2D, 3D histograms with weights / labels.
=> fix: histogram weights not handled correctly in hist / boost conversion

src/uproot/exceptions.py, src/uproot/language/python.py
I normally dislike warnings, but if we made this case an exception, then there would be reasonable-to-do things that wouldn't be possible to do. So, okay, a warning.
=> feat: warn about TBranch name, alias name conflict.

src/uproot/_util.py, src/uproot/interpretation/library.py, tests/test_0637-setup-tests-for-AwkwardForth.py
Swapped for loops for pytest fixtures, so that the with-AwkwardForth code path and the without-AwkwardForth code path are fully tested.
Switching the order with-AwkwardForth and without-AwkwardForth in `test_00` revealed a bug in the fallback path that hadn't been tested (also fixed in this PR).
This PR also removes "FIXME" messages for the old path: it won't be removed because it's a fallback.
I'll ask @aryan26roy to check this over.
=> fix: ensure AwkwardForth fallback path is tested without history.

src/uproot/_dask.py, src/uproot/behaviors/TBranch.py, src/uproot/interpretation/__init__.py, src/uproot/interpretation/grouped.py, src/uproot/interpretation/jagged.py, src/uproot/interpretation/library.py, src/uproot/interpretation/numerical.py, src/uproot/interpretation/objects.py, src/uproot/interpretation/strings.py, src/uproot/models/TBasket.py, tests/test_0017-multi-basket-multi-branch-fetch.py
This is taking over a function from Coffea—adding `TBranch.title` to the `__doc__` parameter of Awkward Arrays—in a centralized way. The only file that is affected to add that feature is library.py (the `Awkward` singleton). Let me know, @lgray, if it works as needed.
All the rest of the changes are to propagate the option down. We don't want to _always_ do this; Coffea just needs a hook to be able to enable it. The `interp_options` mechanism enables us to pass more of these options in in the future.
=> feat: add 'interp_options' mechanism and ak_add_doc.

tests/test_0420-pyroot-uproot-interoperability.py
I'm going to fast-track this, adding
```diff
@@ -50,7 +50,8 @@ def test_write_pyroot_TLorentzVector(tmp_path):
with uproot.recreate(newfile, compression=None) as fout:
fout["something"] = ROOT.TLorentzVector(1, 2, 3, 4)
-    with uproot.open(newfile) as fin:
+    classes = dict(uproot.classes)
+    with uproot.open(newfile, custom_classes=classes) as fin:
uproot_vec = fin["something"]
assert uproot_vec.member("fP").member("fX") == 1
assert uproot_vec.member("fP").member("fY") == 2
```
It's always legal to add `custom_classes` to [uproot.open](https://uproot.readthedocs.io/en/latest/uproot.reading.open.html). Doing so in this case prevents a test from modifying a global variable, `uproot.classes`, which makes the test fail offline. Maybe all `uproot.open` calls in the test suite should …
=> test: make tests parallelizable (custom_classes in uproot.open).

src/uproot/__init__.py, src/uproot/_dask.py, src/uproot/behaviors/TBranch.py, src/uproot/reading.py, src/uproot/writing/writable.py, tests/test_0067-common-entry-offsets.py, tests/test_0345-bulk-copy-method.py, tests/test_0420-pyroot-uproot-interoperability.py
This is similar to https://github.com/scikit-hep/awkward/pull/1905, but for Uproot.
Multi-array-fetching functions (`HasBranches.arrays`, `HasBranches.iterate`, `uproot.iterate`, `uproot.concatenate`, `uproot.dask`) can take `expressions` and `cut` as positional, but `filter_name` onward are all keyword-only. Similarly, `common_entry_offsets` takes `filter_name` onward as keyword-only (no positional arguments).
The single-array fetching function (`TBranch.array`) can take `interpretation`, `entry_start`, and `entry_stop` as positional, but `decompression_executor` onward are all keyword-only.
`uproot.open` and `ReadOnlyFile` can take `file_path` as positional, but the rest are keyword-only.
`ReadOnlyDirectory` and `HasBranches` (`TTree` and `TBranch`) have mapping-like functions (`keys`, …
=> feat: made 'very optional' arguments keyword-only

pyproject.toml, src/uproot/interpretation/library.py, src/uproot/writing/_cascadetree.py
The tests in this PR will fail until the change in https://github.com/scikit-hep/awkward/pull/1919 makes its way into a release, 2.0.0rc5 (probably). Once that happens, these tests will pass and all others will fail.
Follow the plan described in https://github.com/scikit-hep/awkward/pull/1919#pullrequestreview-1196679809.
=> feat: adjust for name change in scikit-hep/awkward#1919.

pyproject.toml, src/uproot/extras.py, tests/test_0637-setup-tests-for-AwkwardForth.py
It works offline with dask-awkward from its `main` branch, but the tests will still fail until a dask-awkward release is made containing dask-contrib/dask-awkward#119. We just need a dask-awkward 2022.12a3, @douglasdavis.
I'm impressed that the `parse_version("1") < parse_version(awkward.__version__) < parse_version("2")` line survived this long in Uproot v5. I simply misunderstood what "`< parse_version("2")` meant: I must have thought that it excluded all the 2.0.0rcX pre-releases, but that's not how version ordering works. Okay. The version range has been fixed, and it no longer has an upper cap. (We have no reason to believe that there will be an Awkward 3.x, or that it might be disruptive.)
The other "fix", twiddling how the tests get data out of an Awkward Array, side-steps the bug …
=> fix: Uproot tests now work with Awkward 2.0.0.

src/uproot/_dask.py, tests/test_0791-protect-uproot-project_columns-from-dask-node-names.py
When computing Dask graphs with a operations inside a `__getitem__`,
```python
da = uproot.dask(skhep_testdata.data_path("uproot-issue-791.root") + ":tree")
da[da.int_branch < 0].compute()
```
Uproot is receiving names like "less-06b0b18209c65504e8506df9da02f75d" as branch names in `project_columns`. The strings we get in `project_columns` should be a strict subset of the strings in the input set of columns. This PR selects that subset, but it shouldn't be happening on the dask-awkward end.
I'm using a version of dask-awkward from git... `7fe448a1d448fa30f09693be0b14634c7968161a` from December 9, 2022.
=> fix: protect Uproot's 'project_columns' from Dask node names.

src/uproot/_dask.py
In `uproot.dask`'s `project_columns` implementations we need to make sure `branches` is not `None` before looping over the argument. (The optimization in `dask-awkward` will run project_columns with `None` branches if the the optimization determines that all original branches are necessary). more info at https://github.com/dask-contrib/dask-awkward/issues/134 and https://github.com/dask-contrib/dask-awkward/pull/131
=> fix: uproot.dask: Protect against `branches=None` in `project_columns`

src/uproot/interpretation/objects.py, tests/test_0808-fix_awkward_form_for_AsStridedObjects.py
AwkwardForth doesn't read class members like `@instance_version`, `@fBits`, ... because they're not data; they're internal ROOT metadata. `AsObjects.awkward_form` was made to agree with the Forms of the as-built Awkward Arrays (in #790), but `AsStridedObjects.awkward_form` was still sneaking this information in.
It wasn't that the `header` and `tobject_header` flags were somehow being unset from their default values (the default value of `False` means to exclude these "`@`" members). The issue was that the list of member names was being taken from `Model._members`, which includes everything.
Now the accumulation of `_strided_awkward_form` excludes the "`@`' members if the `header` and `tobject_header` flags say we should.
=> fix: AsStridedObjects.awkward_form was still including the '@' members.

src/uproot/compression.py
Does this fix the
```python
>>> fut.compute(scheduler="synchronous")
<Array [[469, 459, 188, 17.8], ..., [414, ...]] type='203939 * var * float32'>
>>> fut.compute(scheduler="threads")
Traceback (most recent call last):
...
zstd.ZstdError: decompression error: Corrupted block detected
```
issue, @nsmith-?
=> fix: separate ZstdDecompressor for each thread.

src/uproot/writing/_cascadentuple.py
testing on something real simple:
```python
import uproot
import awkward as ak
def test_writable():
filepath = "/tmp/test.root"
with uproot.recreate(filepath) as file:
akform = ak.forms.RecordForm(
[
ak.forms.NumpyForm("int32"),
],
["one"],
)
file.mkrntuple("ntuple", akform)
array = array = ak.from_iter([{"one_integers":1}])
a = file["ntuple"]
a.extend(array)
assert type(file["ntuple"]).__name__ == "WritableNTuple"
test_writable()
```
and can be read back from Julia
```julia
julia> f = ROOTFile("/tmp/test.root")
ROOTFile with 1 entry and 0 streamers.
/tmp/test.root
└─ ntuple (ROOT::Experimental::RNTuple)
julia> LazyTree(f, "ntuple")
Row │ one
│ Int32
─────┼───────
1   │ 9
2   │ 8
3   │ 7
4   │ 6
5   │ 5
6   │ 4
7   │ 3
8   │ 2
9   │ 1
10  │ 0
```
But ROOT doesn't like it:
```python
>>> …
```
=> feat: [WIP] RNTuple Basic Writing

src/uproot/_awkward_forth.py
I also sorted the dict, to make it easier to spot when something is missing.
=> fix: `_awkward_forth.symbol_dict` was missing `np.dtype(">i1")`

src/uproot/_dask.py
This PR implements the interface (to be merged) defined in https://github.com/douglasdavis/dask-awkward/pull/3 to implement form remapping in `uproot.dask`.
I have confirmed this so far with local testing, ideas for a minimal test would be appreciated!
@jpivarski
=> feat: allow `uproot.dask` to re-map forms at the data source

src/uproot/_dask.py, tests/test_0832-ak_add_doc-should-also-add-to-typetracer.py
This is essentially completing #784, which added docstrings to materialized arrays, but not the typetracers that Dask uses.
=> fix: ak_add_doc should add docs to both the lazy and the materialized array.

src/uproot/_util.py, src/uproot/behaviors/TBranch.py, src/uproot/interpretation/library.py
This came up in Discussion #826 (Issue #833): the AwkwardForth errors occur on an Interpretation that could never have been Awkward anyway.
An early hint was that it was going through [read_object_any](https://github.com/scikit-hep/uproot5/blob/c24159917ea5732ada3bb0b03615707823194197/src/uproot/deserialization.py#L184-L319), which means arbitrary-typed pointers, circular references, and a whole host of things that are beyond the scope of Awkward Array, but the clearest indication was that we got the "Cannot be Awkward" error in TTrees with zero entries—if it could have gotten past the AwkwardForth read, it would have encountered this error, anyway. (It didn't get past the AwkwardForth read because we don't generate AwkwardForth inside `read_object_any`.)
So this PR
* takes the check out …
=> fix: complain about CannotBeAwkward earlier, before reading data.

pyproject.toml
This is a code cleanup PR — we already define `awkward` as a core dependency, so we don't need to repeat this in the other dependency groups now.
=> chore: don't repeat awkward dependency

src/uproot/_awkward_forth.py, src/uproot/containers.py, src/uproot/interpretation/objects.py
@mpad saw factors of 200× speed difference between some TBranches in #850. It turned out to depend on whether any `std::vectors` are empty or not: TBranches that contain any empty `std::vectors` in all entries were slow, those that didn't were fast.
It's because the AwkwardForth code-generation step has to consider, at the end of each entry, whether the code that it has is complete or if it's not complete because it's never observed a given list as occupied (and therefore could learn how many bytes its headers are, if there had been any objects in it). The logic, as-written, would mark an entry incomplete (`var_set = True`) if any list anywhere within it is empty. However, data like this:
```
[[[]], [[]], [[]], [[]], [[]], [[123]]]
```
or this:
```
[[[123]], [[]], [[]], [[]], [[]], [[]]] …
```
=> fix: replaced incorrect AwkwardForth `var_set` logic with a check to see if the Form is complete

src/uproot/containers.py, tests/test_0798_DAOD_PHYSLITE.py
cc @nikoladze and @lgray
Two of the problematic TBranches in #798 have been fixed by a previous PR, probably this one: #851.
The other two had the same error: the first few `std::vectors` in the first entry were empty and the last few were not empty. Stepping through the empty ones created the ListOffsetArray Form node and Forth code multiple times, nesting it each time. (This is entirely in the code-generation stage, and the "input names, output names, variable names, and user-defined words must all be unique" error message was just the first symptom.)
The non-empty `std::vectors` already knew that they're not supposed to keep creating ListOffsetArray nodes. Despite over 3 hours of @nikoladze and me looking at this code, we didn't understand the code path of how the working part is …
=> fix: AwkwardForth was nesting the same ListOffsetArray (same node name) multiple times

src/uproot/behaviors/TH1.py
Possible fix for #883. Uproot-browser can now view histograms from Geant4.
=> fix: histograms from Geant4

pyproject.toml, src/uproot/_dask.py, src/uproot/_util.py, src/uproot/behaviors/TBranch.py, src/uproot/models/TTree.py, tests/test_0603-dask-delayed-open.py
Fixes #891
Example implemented for delayed-open.
---------------
From @jpivarski: implemented for four cases, `open_files=False`,`True` and `library="np"`,`"ak"`.
If any user-specified steps (we're calling them "steps," not "chunks" now) are out of bounds, this raises a `ValueError` in all four cases (though the `open_files=False` cases raise errors later than `open_files=True`).
If steps are specified, all four cases set Dask array `chunks` and dask-awkward `divisions`.
Also new: the `open_files=True` and `library="ak"` case wasn't setting `divisions`, though it should have been.
=> feat: chunk specification in uproot.dask

src/uproot/_dask.py
This PR will add support for dask-contrib/dask-awkward#184 to the uproot input layer, so that unused fields can still be partially represented in the layouts of the loaded arrays.
=> feat: add `unproject_layout` support

README.md, docs-sphinx/basic.rst, pyproject.toml, src/uproot/__init__.py, src/uproot/_dask.py, src/uproot/_util.py, src/uproot/behaviors/TBranch.py, src/uproot/extras.py, src/uproot/reading.py, src/uproot/source/__init__.py, src/uproot/source/s3.py, tests/test_0916-read-from-s3.py
This introduces support for for accessing files from S3. The `minio` client is used to interact with S3 service provider to obtain a presigned http URL that is valid for 7 days. The S3 method for getting objects is not used for simplicity, but also there is an assumption that the HTTP multipart queries might have a better performance.
With regards to choice of URI format, the `s3://<bucket>/<object>` schema as supported by the `aws` tool is implemented with some extensions to allow for non-AWS endpoints. Officially, there are also supposed to be another two formats[1]:
- *virtual-hosted-style* `https://<bucket>.s3.<region>.amazonaws.com/<object>`
- *path-style* `https://s3.<region>.amazonaws.com/<bucket>/<object>` which is "deprecated"
For these urls is not clear how to differentiate …
=> feat: Support reading from S3

tests/test_0930-expressions-in-pandas.py
The test introduced in #930 depends on pandas.
Like other tests, it should be skipped if pandas cannot be imported.
=> chore: skip pandas test if pandas is not installed

tests/test_0637-setup-tests-for-AwkwardForth.py
It wasn't testing `library="ak"` before. Also, it's a small enough file that we can test the whole thing.
=> test: better test for vectorVectorDouble

src/uproot/_dask.py, src/uproot/extras.py
dask-awkward and awkward-pandas are both on conda now.
Also consistently added `-c conda-forge` to the packages that are only on conda-forge (though users would have a problem if they mix conda channels, but we can't force conda channel hygene on them).
Removed the text from the `uproot.dask` docstring about installing Dask, just to ensure that the message is in only one place (error message when you attempt to use a package that isn't there), so that it can be updated in one place. That's the whole reason for having an extras.py, after all.
=> fix: get package import messages up-to-date

tests/test_0755-dask-awkward-column-projection.py
This is an immediate fix, but when dask-contrib/dask-awkward#365 makes it into a release, we should remove the line
```python
pytest.importorskip("pyarrow")  # dask_awkward.lib.testutils needs pyarrow
```
from all of the following files:
* test_0652_dask-for-awkward.py
* test_0876-uproot-dask-blind-steps.py
* test_0700-dask-empty-arrays.py
* test_0755-dask-awkward-column-projection.py
=> fix: tests were failing because dask_awkward.lib.testutils needs pyarrow

src/uproot/_dask.py
* Remove extra {} around the dictionary example.
* Multiline literals are not a thing, convert that to a code block.
=> docs: _dask.py: fix docstring formatting

tests/test_0662-rntuple-stl-containers.py
We're going to need a stable set of tests for vetting #966. Perhaps it hasn't been happening in CI, but tests/test_0662-rntuple-stl-containers.py has been failing for me locally, presumably because #928 is not resolved (and CI is somehow skipping this one?).
=> test: skip RNTuple test until #928 is fixed

tests/test_0603-dask-delayed-open.py, tests/test_0916-read-from-s3.py
We missed this because all of the test-runners that have Dask installed also have dask-awkward installed. In principle, someone might run the tests in an environment that does not.
=> test: skip if dask-awkward, an optional dependency, is missing

src/uproot/_util.py, tests/test_0692_fsspec.py
I scanned all of @lobis's PRs for "XRootDSource" and "source.root" and it only appeared in #971.
We need a test for it, though.
=> fix: typo in `uproot.source.xrootd.XRootDSource` name

tests/test_0965-inverted-axes-variances-hist-888.py
Test 0965 fails:
```
==================================== ERRORS ====================================_____ ERROR collecting tests/test_0965-inverted-axes-variances-hist-888.py _____ImportError while importing test module '/build/source/tests/test_0965-inverted-axes-variances-hist-888.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/nix/store/pzf6dnxg8gf04xazzjdwarm7s03cbrgz-python3-3.10.12/lib/python3.10/importlib/__init__.py:126: in import_module
return _bootstrap._gcd_import(name[level:], package, level)
tests/test_0965-inverted-axes-variances-hist-888.py:5: in <module>
import hist
E   ModuleNotFoundError: No module named 'hist'
```
It seems that the other tests relying on `hist` import it using `hist = pytest.importorskip("hist")`.
I did the same in …
=> fix: remove unused hist import in test_0965

src/uproot/source/chunk.py, src/uproot/source/cursor.py, src/uproot/source/file.py, src/uproot/source/fsspec.py, src/uproot/source/futures.py, src/uproot/source/http.py, src/uproot/source/object.py, src/uproot/source/s3.py, src/uproot/source/xrootd.py
Add types to most of the sources module.
Only added types where I was sure of the type.
I left things such as urls, file paths, etc. untyped instead of typing them as `str` since user may pass a `pathlib` path or similar.
=> chore: add types to most of the `uproot.source` module

src/uproot/_dask.py
Replaces #997 with a PR that exclusively caches the remapped form.
In the original dask-awkward refactoring PR, I treated form remapping as a cheap operation that could be performed multiple times. However, it appears that this was too strong an assumption, and incidentally brings other consequences when performed at worker time, not just at scheduler time.
This PR caches the form remapping, changing our private interface to store the remapping information rather than its factory.
=> fix: cache form remapping to avoid per-chunk workload

src/uproot/source/fsspec.py, src/uproot/source/futures.py
We were passing arguments to the tasks as positional, this makes some of the fsspec sources behave differently because they may have different number / order of arguments.
I also modified the definitions to keep the same as `concurrent.futures.ThreadPoolExecutor`.
I noticied after debugging https://github.com/scikit-hep/uproot5/pull/999 failure.
=> feat: update the executor submit interface to take keyword arguments and be compatible with `concurrent.futures.ThreadPoolExecutor`

src/uproot/_util.py, tests/test_0692_fsspec.py, tests/test_0976_path_object_split.py
Fixes https://github.com/scikit-hep/uproot5/issues/1006.
Add additional tests to cover more cases.
=> fix: url and object splitting for local files

src/uproot/_util.py, tests/test_0001-source-class.py, tests/test_0976_path_object_split.py
Use `fsspec` to get the list of supported uri schemes. Direct the user to this list in case of an invalid scheme.
**Changes**: paths such as `file.root://object-with-too-many-slashes` will now throw a `ValueError` saying that the `file.root://` scheme is not in the list of valid schemes.
=> feat: improve uri scheme parsing with list of available schemes from `fsspec`

.github/workflows/build-test.yml, tests/test_0692_fsspec.py
This PR adds an ssh server only to the ubuntu build of the CI to test accessing files over ssh via fsspec.
After testing it I realised that `sshfs` does not implement some interface required by uproot for this to work (`cat_file`) so it raises a `NotImplementedError`. I'm not sure if this is just not implemented and can be implemented or if there is a limitation why this has not been implemented (you cannot request a chunk of a file, you need to request it all?).
We could handle each `fsspec` case separately having a fallback in case some interface is not implemented, but I think it would complicate things too much.
After writing this PR I think it makes sense to raise a more detailed exception if fsspec does not implemented the required interface, so the user can post an issue in the …
=> test: testing sshfs with local ssh server

pyproject.toml, src/uproot/_util.py, tests/test_0692_fsspec.py
After https://github.com/scikit-hep/uproot5/pull/1013 I opened an issue in fsspec https://github.com/fsspec/filesystem_spec/issues/1411 to discuss the issue of not having `cat_files` as part of the interface for the ssh backend.
I realised that I was using the wrong package: `sshfs` which is a third party implementation of an ssh backend (to my defense `s3fs` is the name for the `fsspec` `s3` backend...). `fsspec` already has an ssh backend that can be used if the `paramiko` package is installed. And it implements the `cat_file` interface so it works!
This PR updates the tests to reflect this (now the tests actually access the file over ssh).
**Minor feature**:
I noticed that if the fsspec handler was not being explicitly specified the ssh would faild because it would default to the old …
=> test: use `paramiko` for ssh instead of `sshfs`

src/uproot/source/http.py, tests/test_0001_source_class.py
After doing some benchmarks for the http and fsspec sources, I noticed a significant difference between my "requests-only" implementation and using uproot http source. Mine was correctly doing the multipart request while uproot wasn't. After some debugging I found the reason why: uproot separates the byte ranges with a ", " (comma + space) while I was just using a single comma. This space in the header apparently results in some servers not responding as expected.
At first I though that this failure in the request was due to the significantly large header (just adding the space results in 150 additional characters when retrieving 151 tbaskets as my use-case). But then I realised that the server just didn't understand the request if it had the space.
I am using the following endpoint: …
=> feat: modify how multipart bytes header is built (no space) on http source

pyproject.toml, src/uproot/_util.py, src/uproot/source/fsspec.py
Notice that this PR merges into `main-fsspec` not into `main`. The `main-fsspec` will exist along main for a while. I will make a PR to merge `main-fsspec` into `main`.
=> feat: add fsspec as required dependency

src/uproot/_util.py, tests/test_0001_source_class.py, tests/test_0692_fsspec_reading.py, tests/test_0976_path_object_split.py
Closes #1025 
Bonus features:
- Able to parse object paths with colons in them e.g. file.root:dir/tree:with:colon -> file.root, dir/tree:with:colon
Limitations:
- Uses `.root` file extension as anchor, it's only able to split objects if the file has exactly a `.root` extension. This is technically a breaking change.
=> feat: simplify object path split

.github/workflows/build-test.yml, src/uproot/_util.py, src/uproot/sink/file.py, src/uproot/writing/writable.py, tests/test_0692_fsspec_writing.py
Fixes https://github.com/scikit-hep/uproot5/issues/1029
Add new test
=> fix: processing of `pathlib.Path` argument for writing

src/uproot/source/fsspec.py, tests/test_0302_pickle.py
As discovered in https://github.com/scikit-hep/uproot5/pull/1032 the serialization of the fsspec source wasn't being done correctly.
=> feat: correct fsspec source serialization

pyproject.toml, src/uproot/_dask.py, tests/test_1058_dask_awkward_report.py
Supersedes #1050 
This again boils down to adding a `report=` argument, but now the implementation to actually build the report is significant changed and based on PR https://github.com/dask-contrib/dask-awkward/pull/433 in dask-awkward instead of the combination of #1050 + https://github.com/dask-contrib/dask-awkward/pull/415
@lgray if you could take this for a spin on something that you know will potentially have `OSError` raised, that would be great!
=> feat(draft): add `report=` argument for `uproot.dask`; trigger report collection (take 2!)

.github/workflows/build-test.yml, pyproject.toml
`aiohttp` appears to be available for python 3.12 so we can remove the skip.
I also increased the number of reruns in the pytest command to avoid failure due to flaky xrootd.
=> test: do not skip aiohttp tests for Python 3.12 - update pytest rerun settings

pyproject.toml, src/uproot/source/fsspec.py, tests/test_1063_dask_distributed.py
- https://github.com/scikit-hep/uproot5/issues/1063
=> fix: dask distributed fsspec issue

tests/conftest.py, tests/test_0001_source_class.py, tests/test_0006_notify_when_downloaded.py, tests/test_0007_single_chunk_interface.py, tests/test_0692_fsspec_reading.py, tests/test_0692_fsspec_writing.py
Add a pytest fixture for xrootd server which can be used to serve files locally over xrootd. We might want to switch to use this for all xrootd tests to avoid networking / server issues.
I updated one xrootd test to use this new fixture.
I also renamed the old "server" fixture to "http_server" since now we have more than one server fixture.
=> test: xrootd server fixture

.github/workflows/build-test.yml, tests/test_0692_fsspec_reading.py
test `simplecache`. Made it work with xrootd in https://github.com/CoffeaTeam/fsspec-xrootd/pull/42.
=> test: fsspec cache

src/uproot/_dask.py, tests/test_1058_dask_awkward_report.py
Change `uproot.dask`'s `allow_read_errors_with_report` argument to also allow a tuple of exceptions to be passed in. Original `=True` behavior keeps the `(OSError,)` only tuple
=> feat: allow user to supply tuple of allowed exceptions

pyproject.toml, src/uproot/interpretation/objects.py, tests/test_1063_dask_distributed.py, tests/test_1085_dask_write.py
The TBranch described in #1099 contains many empty lists, and its AwkwardForth code can't be discovered until it sees at least one non-empty list. That happens after cycling from one TBasket to the next (about a dozen TBaskets, actually), and the `context["forth"].vm` state is `None`, rather than nonexistent, due to
https://github.com/scikit-hep/uproot5/blob/e592ae333c2d8d2ee7d65f1a2de1fcb3a8fea13f/src/uproot/interpretation/objects.py#L237
So the check for "Does an AwkwardForth VM exist?" should check for both the missing attribute case and the attribute is equal to None case.
=> fix: state of context["forth"] after an entire TBasket is incomplete

src/uproot/source/fsspec.py
I have not tested this as a fix for #1117, but it seemed like an obviously missing thing that should be filled in anyway.
=> fix: missing '_fh' and '_file' attributes after unpickling

tests/test_0692_fsspec_writing.py
In testing fsspec writing for configurations in scheme + slash_prefix a "\\" directory gets made with what should be temporary files. 
Moving to the tmp_path before creating the file doesn't work, thus we can simply remove the newly created folder. 
We can do this immediately after testing each file (`test_fsspec_writing_local_uri` in `test_0692_fsspec_writing`) or after all the versions of that test have been executed.
=> fix: test suite creates files not in tmp_path

src/uproot/writing/identify.py
Commit ec80b887 broke support for writing histograms that fulfill the Unified Histogram Interface, but are neither from hist nor from boost_histogram. UHI compatible histograms always have a function `variances`, but do not have a `storage_type` attribute, so that attribute should only be checked if the histogram is indeed from boost_histogram.
=> fix: allow writing generic UHI-compatible histograms

pyproject.toml, src/uproot/compression.py
The latest version of cramjam in conda-forge is 2.8.0. With this, the Uproot 5.3.1 release will be able to go into conda-forge without waiting for cramjam to update.
This adds a fallback instead of an error if cramjam doesn't have an LZMA module, and then the minimum version of cramjam can be loosened to 2.5.0. A fallback for something as invisible as compression is a little dangerous because if the Python standard library LZMA behaves a little differently from the cramjam LZMA, we'd have to carefully check that in any debugging.
However, compression algorithms almost always work—I think it's highly unlikely that we'll need to debug it at all—and the corner of space between cramjam 2.8.0 and 2.8.1 is tiny. (If someone actually gets something in the 2.5.0‒2.8.0 range, it's because they're …
=> chore: loosen cramjam version constraint to >=2.5.0

src/uproot/_dask.py, src/uproot/behaviors/TBranch.py, src/uproot/source/chunk.py
Report type is now
```
type: 7 * {
call_time: ?unknown,
duration: float64,
performance_counters: {
num_requested_bytes: int64,
num_requests: int64,
num_requested_chunks: int64
},
args: var * string,
kwargs: var * unknown,
exception: ?unknown,
message: ?unknown,
fqdn: ?unknown,
hostname: ?unknown
}
```
=> feat: Record source performance counters in uproot.dask report

src/uproot/models/TString.py, src/uproot/reading.py, tests/test_0692_fsspec_reading.py, tests/test_1160_std_string_in_TDirectory.py
~~Fixes #1159.~~ (That's a discussion.)
What do you think, @chrisburr? Is `std::string` truly exceptional, such that a special case is warranted, or is this the tip of an iceberg that should be handled in a more systematic way?
(If it's to be handled in a systematic way, I don't know when or by whom.)
=> feat: special case for reading std::string from a TDirectory

src/uproot/_dask.py
This is a follow-up to https://github.com/scikit-hep/uproot5/pull/1120#issuecomment-1982305217, which added arguments to some internal classes in Dask, but didn't update the protocols that described those internal classes.
=> fix: add new Executor arguments to ImplementsFormMappingInfo protocol

.github/dependabot.yml, .github/workflows/build-distributions.yml, .github/workflows/deploy.yml, .github/workflows/upload-nightly-wheels.yml
* Add build distributions workflow that is reusable across other workflows.
* Add upload nightly wheels workflow to upload nightly to Anaconda cloud.
* Use the build distributions workflow in the deploy workflow.
* Group dependabot updates to reduce the number of PRs.
- c.f. sp-repo-review GH212: Require GHA update grouping
https://learn.scientific-python.org/development/guides/gha-basic/#GH212
By using the
```yaml
jobs:
build_wheel:
...
if: github.repository_owner == 'scikit-hep'
uses: ./.github/workflows/build-distributions.yml
```
syntax the "Build sdist and wheel" workflow becomes a step in the following workflows (first box) run as test jobs on another branch where the deploy steps are commented out:
* Upload nightly wheels to Anaconda Cloud
* Deploy to PyPI
=> ci: Add upload nightly wheel and dist build workflows

pyproject.toml
This makes it possible to install/depend on `uproot[xrootd,http,s3]` to decouple the user facing feature from the implementation details in uproot.
Closes #1153
=> feat: Add extras for optional remote access dependencies

tests/test_0692_fsspec_writing.py
I'll try removing the slash, putting it back in, and if that's it, I'll exclude it on Windows.
It's making paths like
```
/C:\Users\runneradmin\AppData\Local\Temp\pytest-of-runneradmin\pytest-0\test_fsspec_writing_local_uri_24\some\path\my%E2%80%92file.root
```
which at some point become `D:/C:`. Right about here:
```
C:\Users\runneradmin\miniconda3\envs\test\lib\site-packages\uproot\sink\file.py:53: in __init__
self._truncate_file(urlpath_or_file_like, **storage_options)
self       = <uproot.sink.file.FileSink object at 0x00000295EDA4AFD0>
storage_options = {}
urlpath_or_file_like = '/C:\\Users\\runneradmin\\AppData\\Local\\Temp\\pytest-of-runneradmin\\pytest-0\\test_fsspec_writing_local_uri_24\\some\\path\\my%E2%80%92file.root' …
```
=> test: is the leading slash breaking Windows tests?

pyproject.toml
Because of aio-libs/aiohttp#1115, the aiohttp library can let an HTTPS connection dangle for one event longer than pytest or Python allows, triggering an "unclosed transport" ResourceError.
We _do_ want to be sticklers for open file handles in our tests, so the `filterwarnings` entry for this was made very narrow, to only include this case.
@lobis, did you know about this? Is the alternative of having `FSSpecSource` do
```python
await asyncio.sleep(0)
```
when it goes out of a context manager viable?
=> test: allow aiohttp to leak HTTPS connections

src/uproot/compression.py
I've [pre-released v2.8.3-rc1](https://pypi.org/project/cramjam/2.8.3rc1/#files), which has the XZ/LZMA stuff now as `cramjam.xz`. 
Would rather not break things for you, so until releasing `2.8.3`, I think this change, or something like it, should happen here or >= 2.8.3 will look like it doesn't have xz/lzma support.
xref https://github.com/milesgranger/cramjam/issues/126
=> fix: change expected xz/lzma module location on cramjam

src/uproot/source/fsspec.py
This allows filesystem implementations to use possibly more optimal request strategies, such as fsspec-xrootd's use of vector_read.
It's not clear to me if all fsspec implementations support this, and if it will generally perform better or not. At least for xrootd it is an improvement.
=> feat: Use cat_ranges in fsspec source

src/uproot/writing/_cascadetree.py, tests/test_1186_dtype_might_raise_ValueError.py
=> fix: `np.dtype(branch_type)` might raise ValueError, not just TypeError

.github/workflows/build-test.yml, src/uproot/_util.py, src/uproot/interpretation/numerical.py, src/uproot/source/cursor.py, src/uproot/streamers.py, tests/test_0692_fsspec_reading.py, tests/test_0692_fsspec_writing.py, tests/test_1070_pandas_dataframe_building_performance_fix.py, tests/test_1120_check_decompression_executor_pass_for_dask.py, tests/test_1189_dask_failing_on_duplicate_keys.py
Following on scikit-hep/awkward#3064, Uproot needs some fixes for NumPy 2.0 as well.
This fixes Uproot and adds new tests for NumPy 2.0 on all 3 platforms.
=> fix: update for NumPy 2.0

src/uproot/models/RNTuple.py, tests/test_1191_rntuple_features.py, tests/test_1191_rntuple_fixes.py
Very simple RNTuple files can be read, but currently there are issues reading more complex files. In this PR, I'll be working towards fixing as many issues as I can find. I'll update this description with more information once it's ready for review.
=> fix: various RNTuple fixes

src/uproot/_util.py, tests/test_0008_start_interpretation.py, tests/test_0416_writing_compressed_data.py
Reported at https://github.com/dcwatson/deflate/issues/42.
Here's a build in `main` that was failing because of `deflate`
https://github.com/scikit-hep/uproot5/actions/runs/8959087137
This started sometime between April 25 and April 29, 2024.
=> test: desable 'deflate' tests on MacOS; it fails on import

src/uproot/behaviors/TBranch.py
This is an addendum to PR #838, which fixed #833 by checking for `CannotBeAwkward` errors earlier (before reading data).
The previous PR added a `TBranch._awkward_check` on all TBranches in `branchid_interpretation`, but since there wasn't a list of actual TBranch objects (with methods like `_awkward_check` that you can call), the previous PR made a lookup dict called `branchid_to_branch` for this purpose, getting the `TBranch.cache_key` ("branch id") to TBranch object mapping from `ranges_or_baskets`.
However, it looks like `ranges_or_baskets` can have fewer branches than `branchid_interpretation`. Obviously I didn't think so when I wrote PR #838[^1], but the bug @gordonwatts found can only have happened if this is the case. It doesn't seem implausible: the `branchid_interpretation` list …
=> fix: not all branchid_interpretation are necessarily in ranges_or_baskets

src/uproot/behaviors/TBranch.py
The duplicate-checking should be checking against the full path, with slashes, not the `branch.name`. This passes the same tests as before (the Delphes file had no TBranches nested within TBranches), but it should fix CoffeaTeam/coffea#1080.
=> fix: bug in PR #1189's 'ignore_duplicates' implementation

src/uproot/writing/_cascade.py, tests/test_1212_dont_let_update_mess_up_file_version.py
When `uproot.update` was reading in a file, it used to unconditionally subtract 1000000 from the `TFile::fVersion` that it read:
https://github.com/scikit-hep/uproot5/blob/e9440995e0e6649bf8ea8634185d758602179a55/src/uproot/writing/_cascade.py#L2175-L2188
The offset of 1000000 is how ROOT distinguishes between files with (some) 64-bit seek positions and files that are all 32-bit. Uproot's `FileHeader.version` holds the real version number, without the offset, and puts the offset back in if needed:
https://github.com/scikit-hep/uproot5/blob/e9440995e0e6649bf8ea8634185d758602179a55/src/uproot/writing/_cascade.py#L2093-L2100
But it was _unconditionally_ subtracting 1000000 from the files it read, even if the file was fully 32-bit, as most are (because it only starts to matter for files …
=> fix: don't let uproot.update mess up the TFile fVersion

src/uproot/_util.py, tests/test_0008_start_interpretation.py, tests/test_0416_writing_compressed_data.py
Fixed by dcwatson/deflate#42 in deflate 0.6.1 (and the broken 0.6.0 has been yanked).
I tested it locally on my (M2) Mac; I expect it to breeze through the test suite, so I'll just enable auto-merge.
Thanks for the quick fix, @dcwatson!
=> test: reinstate 'deflate', now that it works on MacOS

src/uproot/models/RNTuple.py, tests/test_0662_rntuple_stl_containers.py, tests/test_1191_rntuple_fixes.py
This PR fixes reading RNTuple switch data, which is now 96 bits as opposed to 64 bits. These are used to encode `std::variant` types. I re-enabled a test for them, which I didn't realize was being skipped.
Also, as a minor thing, I disabled another RNTuple test because the test file takes a relatively long file to download, and sometimes the server seems to get stuck.
=> fix: add support for new RNTuple switches

.github/workflows/deploy.yml
* Add generation of GitHub artifact attestations to built sdist and wheel before upload. c.f.:
- https://github.blog/2024-05-02-introducing-artifact-attestations-now-in-public-beta/
- https://docs.github.com/en/actions/security-guides/using-artifact-attestations-to-establish-provenance-for-builds
=> ci: Add GitHub artifact attestations to package distribution

src/uproot/streamers.py, tests/test_1221_AwkwardForth_bug.py
We've never before had a C++ class with members in the following pattern:
1. some basic type (int, float, bool...)
2. some not basic type (string, collection, class...)
3. more than one basic types
but it came up in #1221. It revealed a bug in which AwkwardForth statements are supposed to be generated from the last `fields`/`formats` list to be filled (these variables are both lists of lists), but the old code was looking at the first.
This was in the "AwkwardForth testing E" block, for the case in which there's more than just one `fields`/`formats`.
* If part 3 (above) has no more than one basic type, then we'd be in "AwkwardForth testing D", which was correct (`fields[-1][0]` and `formats[-1][0]`, with the `-1` in the first index).
* If there was no part 1 (above), then `fields[0] is …
=> fix: 'AwkwardForth testing E' should use the last `fields`/`formats`, not first

tests/test_0927_dont_assume_uproot_in_global_scope_in_TPython_Eval.py, tests/test_0940_feat_add_TLeafC_string_support.py, tests/test_0965_inverted_axes_variances_hist_888.py
Issue #1237 needs to be understood; it's not even clear yet whether it's Uproot using PyROOT incorrectly or it's a bug in ROOT itself. For now, though, we need a release that includes almost all of the tests.
=> test: skip test_0927 because of #1237 (temporary)

.github/workflows/build-test.yml, README.md
We've been testing against Python 3.12 for a long time now (since #980), but somehow forgot to declare that we support this version in the metadata.
Also, since NumPy 2 has been released, we should switch to testing for its absence, rather than its presence, so that both NumPy 1 and NumPy 2 are included in at least one test.
=> chore: declare support for Python 3.12 and switch to testing NumPy < 2

src/uproot/interpretation/library.py
Maybe this `form` is specially constructed to always have a `"parameters"` key, but the general protocol for Awkward Form JSON doesn't require it. Thus, this PR replaces every attempt to extract `form["parameters"]` with `form.get("parameters", {})`. All of these cases are in the object → Awkward conversion that only runs if AwkwardForth failed to run. (It's the Uproot 4.x code, left in as a fallback if the much faster Uproot 5.x workflow doesn't work.)
The fundamental cause of #1244 might be inconsistent construction of that `form` (a corner case that fails to add the `"parameters"` key), and rather than fixing that at the producer end, this PR fixes it on the consumer end.
=> fix: don't require Form JSON to have 'parameters'

src/uproot/source/futures.py, tests/test_1254_test_threadpool_executor_for_dask.py
Looks like this was missing when the function got rebuilt. A test added with None and 1 max_workers arguments in the style of PR#1120, let me know if names should be changed
=> fix: set _max_workers in ThreadPoolExecutor with non-None initializer

src/uproot/models/RNTuple.py, tests/test_1223_more_rntuple_types.py
This PR adds support for a couple of RNTuple types that are currently not supported, namely `std::atomic<T>` and `std::bitset`. I'll make a PR to `scikit-hep-testdata` to add those, and then set up some tests here.
=> feat: add support for more RNTuple types

src/uproot/behaviors/TBranch.py
Very rarely, TBranches with subbranches contain data, usually (unnecessary/ignorable) counts of the subbranches' data per entry. The interpretation for any TBranch with subbranches is `uproot.AsGrouped`, which ignores any of the TBranch's own data and makes it a RecordArray of its subbranches instead.
This is correctly accounted for in the `arrays` (dict of outputs) by assigning the corresponding value to `None` (so that [this event loop](https://github.com/scikit-hep/uproot5/blob/80e780347c2dc40c7004a41c22dfc743ba33f008/src/uproot/behaviors/TBranch.py#L3091-L3110) won't wait for any data to be read).
In the usual case, the TBranch with subbranches does not have any data, so no ranges are added to `ranges_or_baskets`. (`branch.entries_to_ranges_or_baskets` returns an empty list.) However, …
=> fix: apply `TBranch.array`'s veto of `AsGrouped` from `ranges_or_baskets` to `HasBranches.arrays` and `HasBranches.iterate`

src/uproot/writing/_cascadetree.py, tests/test_1264_write_NumPy_array_of_strings.py
The lack of an `import uproot` was an oversight. Most string-writing uses Awkward Arrays directly, but it's possible to get arrays of strings directly from NumPy (`dtype="U#"`). Since our machinery requires contiguous, jagged string data, we must require the Awkward library to do the writing (which might still be a surprise to someone who tries this without installing Awkward), but at least now Uproot knows that it needs to import it.
=> fix: explicit 'import awkward' needed to write NumPy strings

src/uproot/interpretation/objects.py
@nikoladze found a performance bug: if the first whole TBasket has inconclusive AwkwardForth, the code (before this PR) concatenated everything and ran the whole array through a generic iterable → Awkward Array transformation. The problem is that almost all of the data had been an Awkward Array already, all but the one TBasket with inconclusive AwkwardForth.
This PR adds an extra check for this case. If the list of basket-arrays is only partially Awkward, it converts the non-Awkward ones to Awkward individually so that the concatenated array doesn't have to be passed through the unnecessary generic iterable → Awkward Array transformation.
(There aren't any tests for this because it's based on private data.)
=> perf: if first whole TBasket has inconclusive AwkwardForth

src/uproot/models/RNTuple.py
Changes made in RNTuple model:
- Bug-fix: when reading arrays from more than one cluster, data was not identical to TTree. The reason for this was improper array concatenation in case of offset values. More information in here: https://gist.github.com/giedrius2020/c1ca87784779418ee3e938aaca31ff75 
- Added a function to filter wanted key values in `def keys()`
- Minimal change: changed existing "filter_names" variables to "filter_name", because that is how the variable was called in TTree model.
=> fix: RNTuple ug-fixing offset array concatenation, adding filter_name

README.md
Okay, so I'm leaving this as manual because the automated version doesn't show a range—it lists every Python version separately. This would make the badge too big, and I don't want the badges to use so much space. They're carefully arranged in two rows just to keep them from being overwhelming.
=> docs: Uproot only supports Pythons 3.8 through 3.12

pyproject.toml
`xxhash` is currently a strict dependency for reading RNTuples (see #1271). We could simply remove the line that uses `xxhash` to verify checksums, but given that it is now available in Pyodide and it will unquestionably be needed for writing RNTuples, then it makes sense to add it as a dependency now.
Once this is merged, I will also start using it more extensively for RNTuple reading.
Closes #1271.
=> chore(deps): add xxhash dependency

tests-wasm/test_1272_basic_functionality.py
The Pyodide test where a file is read over http has been a little unstable as it randomly has been timing out. I replaced the test with one that uses a smaller file that is hosted on GitHub, so it should be a lot more reliable.
=> chore(ci): replace pyodide http test to make it more stable

.github/workflows/build-test.yml
Miniforge and Mambaforge are now equivalent, so the latter has been deprecated. There are a bunch of warning messages about this on CI runs, so this PR is mainly to clean those up. The rest of the warnings are out of our control, but I've seen that there's open PRs that will fix some of them.
=> chore(ci): switch to miniforge

.github/workflows/build-test.yml, pyproject.toml
Also using uv for the vanilla job
=> ci: test on 3.13

src/uproot/source/coalesce.py
This fixes #1257 - the current read coalescing algorithm has a loop over ranges (to determine `Cluster.stop`) for every range added to a `Cluster` leading to a somewhat quadratic scaling. This can be fixed by having a private `_stop` attribute that is updated in an `append` method. The downside is that now `.append` has to be used to append new ranges to a `Cluster`. Since this is not really a user facing class i think that should be acceptable.
Using the example TTree from #1257 
```python
import uproot
import numpy as np
num_baskets = 1_000
num_per_basket = 1_000
num_branches = 50
with uproot.recreate("test.root") as f:
for i_chunk in range(num_baskets):
chunk = {f"branch{i}": np.random.rand(num_per_basket) for i in range(num_branches)}
if "tree" in f:
f["tree"].extend(chunk)
else: …
```
=> perf: improve performance for read coalescing

pyproject.toml
There was a bug in the new Selenium version that is causing the Pyodide tests to fail (see #1326). I'm pinning Selenium to the previous version until they make a new release.
=> fix(ci): pin selenium version to fix pyodide tests

src/uproot/containers.py
Commit [#cdaf9a7](cdaf9a7) adds an `__array__` method to STLVector in containers.py [L1544](https://github.com/scikit-hep/uproot5/blob/afca74c2af16641299abfbf91935e8010d601111/src/uproot/containers.py#L1544) and [L1659](https://github.com/scikit-hep/uproot5/blob/afca74c2af16641299abfbf91935e8010d601111/src/uproot/containers.py#L1659).
However, the method tries to return an attribute that does not exist. I think it should return `self._values` and not `self._vector`
```python
def __array__(self, *args, **kwargs):
return numpy.asarray(self._vector, *args, **kwargs)
```
should be:
```python
def __array__(self, *args, **kwargs):
return numpy.asarray(self._values, *args, **kwargs)
```
=> fix: missing attribute in __array__ method of STLVector

src/uproot/interpretation/library.py, tests/test_1321_pandas_changed_api_again.py
Before Uproot 5, we had
https://github.com/scikit-hep/uproot5/blob/b36a0229391c00e101fdbfd56925afa9e2bd2ebb/src/uproot/interpretation/library.py#L1131-L1134
to allow for different Pandas APIs before and after Pandas 0.24. But Pandas 0.24 is ancient, and I decided that we don't need to handle that anymore in #734 (which made a lot of changes, removing the explode-to-Pandas behavior).
But at some point in recent history, the attribute switched from `Index.arrays` back to `Index.values`. There's an `Index.array`, but it's a NumpyExtension, rather than a plain NumPy array, and `np.add` _might_ prefer the real NumPy array.
=> fix: adjust for Pandas changing its API again

pyproject.toml, src/uproot/_dask.py
c.f. https://github.com/dask-contrib/dask-awkward/pull/556
There don't appear to be any other places where uproot directly accesses dask innards.
=> fix: uproot was exposed in one place to dask's _task_spec overhaul

src/uproot/models/RNTuple.py, tests/test_1159_rntuple_cluster_groups.py, tests/test_1191_rntuple_fixes.py, tests/test_1347_rntuple_floats_suppressed_cols.py
This PR fixes #1357. Now multiple cluster groups are handled correctly. Internally, it just groups all clusters together into a single group. I couldn't think of any reasons to keep track of different groups, but we can implement that later if necessary.
=> fix: support RNTuples with multiple cluster groups

tests/test_0001_source_class.py
It returns 200, rather than 206, for our wrong-page examples now. There might be a good way to replace this test, but for now I'm disabling it. We have plenty of other tests that check the HTTP backend. (This test is from 0001, which tested HTTP without any ROOT files because it was written at a time when only the backend handlers existed.)
=> test: adjust for changes in example.com

src/uproot/interpretation/identify.py, tests/test_1229_const_in_typename.py
=> fix: support `const` in typename

.github/workflows/deploy.yml
=> fix: use trusted publishers for publishing releases to PyPI

tests/test_0840_support_tleafG.py
~ROOT was updated to 6.32.8 in `conda-forge` and it seems to have some issue with Python 3.9. Given that the issue is with ROOT and not Uproot, and also that Python 3.9 will reach its eand-of-life later this year, I'm just disabling this test for Python 3.9.~
EDIT: See comments below
=> test: fix broken test

src/uproot/models/RNTuple.py
I changed things so that untyped fields now show up in `keys`. Previously, I was ignoring those since I thought they would not be useful, but that's not true. Also, for now I still ignore fields whose name starts with `_`, but maybe I'll also change this later so that everything appears even though it might come with a lot of garbage.
I also changed the `keys` function so that it takes some arbitrary kwargs and simply ignores them. This fixes #1350, but it is a temporary solution, as coffea needs to switch to using the right kwargs once they fully move to using RNTuples.
The keys function is still missing most functionality, but in the interest of having coffea working, I'll leave that for a future PR.
=> fix: show untyped fields and make keys compatible with coffea

.github/workflows/deploy.yml
Restrict to the environment set for the trusted publisher
=> fix: restrict to the environment set for the trusted publisher

pyproject.toml, src/uproot/_dask.py, src/uproot/behaviors/TBranch.py, tests/test_1375_extend_ak_add_doc.py
---
- Access to C++ typename info for each tree branch is essential in building COFFEA schema for files generated with EDM4HEP.
- Similar to how  `ak_add_doc`  is used to add the `__doc__` parameter to forms, `ak_add_typename` could be used to add  the C++ typename of the branch in parameters.
- This is an attempt to solve this feature request [#1369](https://github.com/scikit-hep/uproot5/issues/1369) posted by @ianna in response to the discussions among @jpivarski @ianna @davidlange6 and @prayagyadav
---
Bash:
```bash
wget https://github.com/prayagyadav/coffea/raw/refs/heads/test-typenames-swan/tests/samples/p8_ee_WW_ecm240_edm4hep.root
```
Python:
```python
file = "p8_ee_WW_ecm240_edm4hep.root"
tree = "events"
events = uproot.dask(file+":"+tree, open_files=False, ak_add_doc=True, …
```
=> feat: Optional support to add c++ typenames to parameters in uproot.dask

pyproject.toml, tests/test_0692_fsspec_writing.py
This PR introduces a test to check that we can correctly write via XRootD (see https://github.com/scikit-hep/uproot5/issues/1252).
This test fails with current fsspec-xrootd, but it succeeds when running with the changes introduced in https://github.com/scikit-hep/fsspec-xrootd/pull/76.
We can thus decide to either merge it now but skip the test, or wait until https://github.com/scikit-hep/fsspec-xrootd/pull/76 is merged (and a new version released) and then merge it.
=> fix: test to check that we can write via xrootd

src/uproot/_dask.py
Enables https://github.com/dask-contrib/dask-awkward/pull/565 for `uproot.dask`.
Example:
```python
import uproot
import dask_awkward as dak
array = uproot.dask({"foo.root": "tree_name"})
key, _ = next(iter(array.dask.keys()))
needs = {key: ["A", "C"]}
optimized_array = dak.manual.optimize_columns(array, needs)
concrete_array = optimized_array.compute()
```
`key` corresponds to the key of the `from-uproot` IO layer. `needs` can have multiple keys that point to various projectable IO-layers.
=> feat: enable manual column optimization with dask-awkward

.github/workflows/build-test.yml
fixes https://github.com/scikit-hep/uproot5/issues/1384
XRootD is officially supported on the following platforms:
RedHat Enterprise Linux 8 or later and their derivatives
Debian 11 and Ubuntu 22.04 or later
macOS 13 (Ventura) or later
Support for other operating systems is provided on a best-effort basis and by contributions from the community.
=> chore: add XRootD on macos

src/uproot/models/RNTuple.py, src/uproot/writing/_cascadentuple.py, src/uproot/writing/writable.py, tests/test_1356_basic_rntuple_writing.py, tests/test_1395_rntuple_writing_lists_and_structs.py
This PR extend the writing functionality for RNTuples quite a bit. It adds the following:
- Lists of booleans
- Lists of strings
- Jagged arrays (including nested jagged arrays)
- Rectangular arrays
- Structs
- Lists of structs
- Optional types
- Union types
=> feat: all essential RNTuple writing functionality

.github/workflows/build-test.yml
I'm pinning the Mamba version that the CI uses so that it stops being so unreliable. The issue was reported in conda-incubator/setup-miniconda#392 but it's been a while and it hasn't been fixed. The suggestion they have there is to pin the Mamba version, so that's what I'm doing. I'll run the tests a few times to make sure that this fix works and then I'll mark it as ready for review.
Closes #1391
=> ci: switch to micromamba

src/uproot/writing/_cascadentuple.py, src/uproot/writing/writable.py
RNTuple data was being stored fully uncompressed, which was pretty wasteful. This small PR makes it so that it is stored compressed with the compression setting from the file. It would be good to have the option of selecting compression settings in a more granular way (i.e. per field or column), but I'll have to think a bit more how to implement this since it would make more sense to specify it per column, but it would be a lot easier to specify it per field.
=> fix: compress RNTuple column data

src/uproot/const.py, src/uproot/writing/_cascadetree.py
In #1135 there are some discussion about writing batches of data that are too big to fit in a TBasket. I added more detailed error messages so that it is clear what went wrong, since the way it currently crashes is not very informative.
=> chore: better error message when writing TBaskets that are too large

src/uproot/_dask.py, src/uproot/behaviors/RNTuple.py, tests/test_1223_more_rntuple_types.py, tests/test_1412_rntuple_dask.py, tests/test_xxxx_rntuple_dask.py
This PR adds the option of reading RNTuples with Dask (at least the basic functionality).
=> feat: RNTuple reading with Dask

src/uproot/writing/_cascadentuple.py, tests/test_1395_rntuple_writing_lists_and_structs.py
This PR adds support for writing `ListArray`s to RNTuples. RNTuples have an analogue for this, so they are converted to `ListOffsetArray`s before writing them.
There are still some array types that can't be written, but each of them requires special handling since again there are no analogues in RNTuple. I'll continue to add them over time.
=> feat: support writing ListArrays to RNTuples

.github/workflows/build-test.yml, tests-wasm/utils.py
I'm updating the version of Pyodide that the CI uses to see if it fixes the issue we started to see in #1420.
=> ci: pin Chrome version for Pyodide tests

src/uproot/writing/_cascadetree.py
Fixes problem with 0-length arrays and writing, e.g.:
```python
import uproot
events = uproot.dask({"coffea/tests/samples/nano_dy.root": "Events"})
uproot.dask_write(
events[events.nJet > 10],  # cuts away all events
destination="skimtest/",
prefix="nano_dy/skimmed",
compute=True,
)
```
=> fix: issue with empty big_endian array

.github/workflows/build-distributions.yml, .github/workflows/build-test.yml, .github/workflows/deploy.yml, .github/workflows/upload-nightly-wheels.yml, CONTRIBUTING.md, pyproject.toml
Using more uv (faster), switching to dependency groups. `uv run ...` now works.
Includes restriction on dask due to https://github.com/dask/dask/pull/11859.
=> chore: move to using dependency-groups

pyproject.toml
The version of Dask was constrained in #1427 since we thought that they introduced a bug. However, the issue seems to be with the interface between `dask-awkward` and `dask`, so they are taking care of it on that side (see https://github.com/dask-contrib/dask-awkward/pull/588).
=> chore(deps): unconstrain Dask dependency

src/uproot/behaviors/TBranch.py
The notifications queue in _ranges_or_baskets_to_arrays cannot be aware of chunk requests in flight because the queue only gets pushed to when we receive the returned chunk data. If we have the necessary array in cache, then we exit this function and fire-and-forget chunk requests causing extra network traffic, and more to the point, potential race conditions between receiving chunks and closing the file on teardown.
Fixes https://github.com/scikit-hep/coffea/issues/1331
=> fix: Only dispatch requests to Source if we actually will use them

src/uproot/source/fsspec.py
FSSpecSource uses an entirely stateless interface for the actual reading, so this file handle is now an unused remnant.
=> fix: Remove unused file handle

.pre-commit-config.yaml
Almost every week there is a PR updating some pre-commit hook, and almost always they don't make any difference. I'm changing the autoupdate schedule so that it only runs monthly.
Henry convinced me to leave the dependabot updates on a weekly schedule since they don't trigger as often and are more important.
=> ci: change pre-commit autoupdate to a monthly schedule

src/uproot/behaviors/TBranch.py
This PR fixes #1442 (at least partially). It's not clear to me why this getter is needed, but it has a huge performance cost, so I switched to using the branch names directly.
This change gives it a huge boost in performance for trees with many branches, although it is still significantly slower than Uproot3.
For comparison, I generated a file with 1000 branches, as done in #1442 and the output of
```python
%timeit uproot.open("test.root:df").arrays(library="pd")
```
went from
```
3.07 s ± 46.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
to
```
353 ms ± 7.82 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
@ianna do you know why this getter could have been needed in the first place? All the tests seem to pass, so I'm not sure why it was needed.
=> perf: faster reading of files with many branches

src/uproot/behaviors/RNTuple.py, src/uproot/const.py, src/uproot/models/RNTuple.py, src/uproot/writing/_cascade.py, src/uproot/writing/_cascadentuple.py, src/uproot/writing/writable.py, tests/test_1395_rntuple_writing_lists_and_structs.py
This is still a work in progress. I'll update the description with the highlights once I'm done.
=> refactor: RNTuple writing improvements

pyproject.toml
We need to skip the latest version of fsspec since they broke something. They already fixed it, but haven't made a new release. We need this so that the CI can pass on other PRs.
=> chore: skip broken version of fsspec

src/uproot/pyroot.py, tests/test_0705_rntuple_writing_metadata.py, tests/test_1356_basic_rntuple_writing.py, tests/test_1395_rntuple_writing_lists_and_structs.py
There `TPython::Eval` api was deprecated in ROOT 6.34 and removed in 6.36, so we have to switch to `TPython::Exec`.
The CI doesn't test with ROOT 6.36, but it works for me locally with 6.37.
Closes #1460
=> fix: resolve issues with ROOT 6.36+

src/uproot/behaviors/RNTuple.py, src/uproot/models/RNTuple.py, tests/test_1250_rntuple_improvements.py, tests/test_1406_improved_rntuple_methods.py, tests/test_1411_rntuple_physlite_ATLAS.py
This PR hides the anonymous fields present in RNTuples. I made this a draft because I want to spend some more time thinking about this to make sure everything that people might want to access is actually easily accessible.
This is a rough first draft that has some downsides. For example, if you have a tuple field, the underlying data in each position of the tuple is stored in fields `_0, _1, ...`, so those would be hidden, but those should actually be accessible. Similarly, if you have an array of structs, let's say an array of electrons, then the members get stored in `_0.pt, _0.eta, ...`, so again those would be hidden, but should actually be accessible.
The tricky part that I'll have to figure out is how to separate "key paths" from the "real paths" inside the RNTuple (e.g. …
=> fix: hide anonymous RNTuple fields by default

src/uproot/models/RNTuple.py, tests/test_1223_more_rntuple_types.py, tests/test_1492_rntuple_hidden_keys.py
This PR fixes a couple of things that I missed in #1469.
I made all subfields of variants hidden, since they cannot be accessed directly in a consistent way. Instead, the entire variant field needs to be read.
For example, with the example in the test
```python
data = ak.Array(
{
"union1": [
{"a": 1, "b": 1},
"two",
{"a": 3, "b": 3},
"four",
"five",
],
"union2": [
{"a": 1, "b": 1},
{"a": 2, "b": 2, "c": 2},
{"a": 3, "b": 3},
{"a": 4, "b": 4, "c": 4},
"five",
],
}
)
```
if one tried to do `rntuple["union1.a"]` one would get 2 elements, but it should be length 5 to be consistent. One could argue that in these cases we can just insert `None`s to make it the right shape, but I think the second example shows it's a bad idea in general. In that case, `rntuple["union2.a"]` would be have to …
=> fix: hide some subfields for variant and atomic fields

src/uproot/behaviors/RNTuple.py
This PR improves the show method on RNTuple so that it better shows the structure. This was inspired by UnROOT, which does a much better job of displaying the contents of an RNTuple.
This change breaks the api, but I think it's fine since `show` is something you would only use interactively and not in some existing script.
I still have to do some polishing and maybe add colors.
=> feat: better show method for RNTuples
