scikit-hep/uproot5

- tests/test_0099-read-from-file-object.py
- uproot4/__init__.py
- uproot4/_util.py
- uproot4/behaviors/TBranch.py
- uproot4/reading.py
- uproot4/source/object.py
> Read file-like objects as a new kind of Uproot Source.

- docs-sphinx/basic.rst
- uproot4/__init__.py
- uproot4/behaviors/TBranch.py
- uproot4/cache.py
- uproot4/reading.py
- uproot4/source/futures.py
> Fix memory leak in parallel processing.

- uproot4/behaviors/TBranch.py
Removes a print statement introduced in #101. Closes #108.
> Remove superfluous print statement

- uproot4/__init__.py
- uproot4/_util.py
- uproot4/exceptions.py
Fixes #119. 
Seems to work pretty well.
> feat: show similar keys first on KeyInFile error

- tests/test_0046-histograms-bh-hist.py
- tests/test_0058-detach-model-objects-from-files.py
- tests/test_0167-use-the-common-histogram-interface.py
- uproot4/behaviors/TAxis.py
- uproot4/behaviors/TH1.py
- uproot4/behaviors/TH2.py
- uproot4/behaviors/TH2Poly.py
- uproot4/behaviors/TH3.py
- uproot4/behaviors/TProfile.py
- uproot4/behaviors/TProfile2D.py
- uproot4/behaviors/TProfile3D.py
Generalizing https://github.com/henryiii/uhi/blob/master/uhi/typing/plottable.py .
> Use the common histogram interface.

- tests/test_0046-histograms-bh-hist.py
- tests/test_0058-detach-model-objects-from-files.py
- tests/test_0167-use-the-common-histogram-interface.py
- uproot4/behaviors/TH1.py
- uproot4/behaviors/TH2.py
- uproot4/behaviors/TH3.py
- uproot4/behaviors/TProfile.py
Needs tests, 2D and 3D TProfile.
Using internal DType info because https://github.com/scikit-hep/boost-histogram/pull/475 isn't ready yet.
> feat: support TProfile 1D conversion

- .github/workflows/build-test.yml
- pyproject.toml
- setup.cfg
- setup.py
This is an attempt to modernize the setup. This _might_ fix the issue with https://github.com/conda-forge/uproot-feedstock/pull/73 - and is generally much cleaner and nicer being declarative.
> refactor: modernize setup

- uproot/behaviors/TH1.py
- uproot/behaviors/TH2.py
- uproot/behaviors/TH3.py
> fix: kind was not implemented on normal histograms

- uproot/behaviors/TH3.py
As soon as @giammi56/[giammi56](https://stackoverflow.com/users/14010009/giammi56) confirms that this fixes the above-mentioned StackOverflow issue, I'll merge this PR. (And if the tests pass.)
Thanks!
> Fix TH3's 'to_numpy' (https://stackoverflow.com/q/65632670/1623645).

- .github/workflows/build-test.yml
- README.md
I'm making this PR to check if conda-forge was fixed correctly I don't mind if it's merged or just closed.
> Re-enable Python 3.5 CI

- requirements-dev.txt
- tests/test_0167-use-the-common-histogram-interface.py
- uproot/behaviors/TH1.py
Adding interface from scikit-hep/boost-histogram#483.
> feat: to boost histogram interface support

- uproot/source/xrootd.py
> Add timeout to vector_read

- uproot/reading.py
> Make MultithreadedXRootDSource the default for xrootd files

- docs-sphinx/basic.rst
> fix typo events -> uproot

- .github/workflows/build-test.yml
- src/uproot/deserialization.py
- src/uproot/models/TRef.py
- tests/test_0320-start-working-on-ROOT-writing.py
As a very first step, I add ROOT to one of the tests (Linux, Python 3.8). For the duration of this PR, I'll have the other tests commented out (since they're required, I can't forget to put them back in).
> Start working on ROOT writing.

- src/uproot/_writing.py
- src/uproot/behaviors/TBranch.py
- src/uproot/models/TBasket.py
- src/uproot/reading.py
- src/uproot/writing.py
- tests/test_0405-write-a-histogram.py
- tests/test_0406-write-a-ttree.py
I should try to finish this off today.
> Write a TTree 3.

- docs-sphinx/basic.rst
- src/uproot/version.py
- src/uproot/writing/_cascadetree.py
- src/uproot/writing/writable.py
Follows up on #426 with similar work for TTrees.
> Final tweaks, bug fixes, and performance checks for this stage of Uproot-writing

- src/uproot/behaviors/TBranch.py
- tests/test_0603-dask-delayed-open.py
Solves #602 
Almost done with implementation, but tests are WIP.
I'm not sure why pre-commit is failing (flake8) on a completely unrelated and unaltered file.
> Basic code for delay in opening files

- .github/dependabot.yml
Will help keep actions up to date.
> chore: add dependabot for actions

- setup.cfg
- setup.py
- src/uproot/models/RNTuple.py
- tests/test_9999-rntuple-flat.py
> Primitive Support for RNTuple

- .github/workflows/semantic-pr-title.yml
This is a total [crib](https://idioms.thefreedictionary.com/crib+from) from https://github.com/scikit-hep/awkward/pull/1615.
> ci: Lint PR titles according to conventional commits

- src/uproot/model.py
- tests/test_0278-specializations-for-TParameter.py
This PR is the "v4" version of #717, which ultimately fixes #707.
> fix: regularize ROOT type aliases to C fundamental type names (v4).

- src/uproot/containers.py
For all Interpretations other than AsMap, the non-memberwise case is implemented, and the memberwise case is implemented for only very few (and partially, at that). That's because when I tried making all combinations of STL containers, `std::map` consistently got serialized in a memberwise way, so I had no examples of what non-memberwise serialization looked like.
Earlier this year, however, I found an example: #556, and earlier today, a user encountered it: #744. Apparently, maps of parameter names and values are serialized as memberwise `std::map` in TFormula, which is part of a TF1 that can be attached to a TH1 histogram. So adding this implementation enables reading histograms with attached fit functions.
There's no indication yet that memberwise `std::map` appears in TTrees, so it's …
> feat: implemented NON-memberwise deserialization for AsMap.

- src/uproot/containers.py
Just like #746, but patching Uproot v4.
> feat: implemented NON-memberwise deserialization for AsMap (v4).

- docs-sphinx/basic.rst
This fixes #800, but I'm going to convert it into a Discussion, rather than closing the issue.
It's now Discussion #803.
> docs: update documentation about Pandas; we don't do MultiIndex anymore.

- src/uproot/compression.py
> fix: separate ZstdDecompressor for each thread (re-do)

- src/uproot/containers.py
- tests/test_0841-fix-814.p
- tests/test_9999-fix-814.py
> fix: models should not be wrapped in a ListOffsetForm

- src/uproot/_dask.py
Fixes case where the number of entries is less than the entry start in Dask.
> fix: clamp start and stop

- src/uproot/_util.py
- tests/test_0692_fsspec_reading.py
> fix: correct typo in fsspec globbing

- src/uproot/writing/_dask_write.py
This is a clone of https://github.com/dask-contrib/dask-awkward/pull/459 adapted to uproot.
> fix: better path handling in uproot.dask_write

- pyproject.toml
- src/uproot/extras.py
The condition here is exactly the package condition. :)
> chore: drop dep that never is valid

- src/uproot/containers.py
Result of the discussion [here](https://github.com/scikit-hep/uproot5/discussions/1171)
> feat: add `__array__` method to ROOTRVec, STLVector, and STLSet

- .github/workflows/build-test.yml
Can just set the one job as required.
> ci: add a pass job

- src/uproot/interpretation/identify.py
Not very systematic but I have added some missing signed versions of a few types.
@jpivarski
> fix: Adding signed versions of char,int,short,long for identify branches

- pyproject.toml
Reverts scikit-hep/uproot5#1368
> fix: Revert "fix: pin dask to upper limit"

- src/uproot/behaviors/TBranch.py
Closes https://github.com/scikit-hep/uproot5/issues/1387.
@acampove can you give this a try?
> feat: add entry_start and entry_stop to uproot.concatenate

- CITATION.cff
> chore: update CITATION.cff

- src/uproot/_util.py
- tests/test_1465_ignorecase_extension.py
> fix: ignore case of file extension

- pyproject.toml
- src/uproot/writing/identify.py
This is still in draft since I want to confirm the timeline and make sure that it's not too noisy.
> chore: warn about switching to writing RNTuples by default

- src/uproot/_dask.py
- src/uproot/behaviors/RNTuple.py
This PR resolves some issues with Coffea when reading RNTuples. This PR is tied to https://github.com/scikit-hep/coffea/pull/1311
> fix: resolve issues with Coffea reading RNTuples

- .github/workflows/build-test.yml
- pyproject.toml
I added the Python 3.14 classifier, and changed the CI so that it also tests it.
> chore: officialy support Python 3.14
